[mypy]
plugins = pydantic.mypy

[mypy-httpx_sse.*]
ignore_missing_imports = True

[mypy-vectara.agent_events.types.*]
ignore_errors = True

[mypy-publication.*]
ignore_missing_imports = True
ignore_errors = True
