# This file was auto-generated by Fern from our API Definition.

import os

import pytest
from vectara.client import AsyncVectara, Vectara
from vectara.environment import VectaraEnvironment


@pytest.fixture
def client() -> Vectara:
    return Vectara(
        api_key=os.getenv("ENV_API_KEY", "api_key"),
        _token_getter_override=lambda: os.getenv("ENV_TOKEN", "token"),
        environment=VectaraEnvironment(
            default=os.getenv("TESTS_BASE_URL", "base_url"), auth=os.getenv("TESTS_BASE_URL", "base_url")
        ),
    )


@pytest.fixture
def async_client() -> AsyncVectara:
    return AsyncVectara(
        api_key=os.getenv("ENV_API_KEY", "api_key"),
        _token_getter_override=lambda: os.getenv("ENV_TOKEN", "token"),
        environment=VectaraEnvironment(
            default=os.getenv("TESTS_BASE_URL", "base_url"), auth=os.getenv("TESTS_BASE_URL", "base_url")
        ),
    )
