# This file was auto-generated by Fern from our API Definition.

import typing

from vectara.client import AsyncVectara, Vectara

from .utilities import validate_response


async def test_list_(client: Vectara, async_client: AsyncVectara) -> None:
    expected_response: typing.Any = {
        "users": [
            {
                "id": "id",
                "email": "email",
                "username": "username",
                "enabled": True,
                "description": "description",
                "created_at": "2024-01-15T09:30:00Z",
                "updated_at": "2024-01-15T09:30:00Z",
                "api_roles": ["owner"],
                "api_policy": {
                    "name": "name",
                    "allowed_operations": {"allowed_operations": {"allow_any_resource": True}},
                },
            }
        ],
        "metadata": {"page_key": "page_key"},
    }
    expected_types: typing.Any = {
        "users": (
            "list",
            {
                0: {
                    "id": None,
                    "email": None,
                    "username": None,
                    "enabled": None,
                    "description": None,
                    "created_at": "datetime",
                    "updated_at": "datetime",
                    "api_roles": ("list", {0: None}),
                    "api_policy": {
                        "name": None,
                        "allowed_operations": ("dict", {0: (None, {"allow_any_resource": None})}),
                    },
                }
            },
        ),
        "metadata": {"page_key": None},
    }
    response = client.users.list()
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.users.list()
    validate_response(async_response, expected_response, expected_types)


async def test_create(client: Vectara, async_client: AsyncVectara) -> None:
    expected_response: typing.Any = {
        "id": "id",
        "email": "email",
        "username": "username",
        "enabled": True,
        "description": "description",
        "created_at": "2024-01-15T09:30:00Z",
        "updated_at": "2024-01-15T09:30:00Z",
        "api_roles": ["owner"],
        "api_policy": {"name": "name", "allowed_operations": {"allowed_operations": {"allow_any_resource": True}}},
    }
    expected_types: typing.Any = {
        "id": None,
        "email": None,
        "username": None,
        "enabled": None,
        "description": None,
        "created_at": "datetime",
        "updated_at": "datetime",
        "api_roles": ("list", {0: None}),
        "api_policy": {"name": None, "allowed_operations": ("dict", {0: (None, {"allow_any_resource": None})})},
    }
    response = client.users.create(email="email")
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.users.create(email="email")
    validate_response(async_response, expected_response, expected_types)


async def test_get(client: Vectara, async_client: AsyncVectara) -> None:
    expected_response: typing.Any = {
        "id": "id",
        "email": "email",
        "username": "username",
        "enabled": True,
        "description": "description",
        "created_at": "2024-01-15T09:30:00Z",
        "updated_at": "2024-01-15T09:30:00Z",
        "api_roles": ["owner"],
        "api_policy": {"name": "name", "allowed_operations": {"allowed_operations": {"allow_any_resource": True}}},
    }
    expected_types: typing.Any = {
        "id": None,
        "email": None,
        "username": None,
        "enabled": None,
        "description": None,
        "created_at": "datetime",
        "updated_at": "datetime",
        "api_roles": ("list", {0: None}),
        "api_policy": {"name": None, "allowed_operations": ("dict", {0: (None, {"allow_any_resource": None})})},
    }
    response = client.users.get(username="username")
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.users.get(username="username")
    validate_response(async_response, expected_response, expected_types)


async def test_delete(client: Vectara, async_client: AsyncVectara) -> None:
    # Type ignore to avoid mypy complaining about the function not being meant to return a value
    assert client.users.delete(username="username") is None  # type: ignore[func-returns-value]

    assert await async_client.users.delete(username="username") is None  # type: ignore[func-returns-value]


async def test_update(client: Vectara, async_client: AsyncVectara) -> None:
    expected_response: typing.Any = {
        "id": "id",
        "email": "email",
        "username": "username",
        "enabled": True,
        "description": "description",
        "created_at": "2024-01-15T09:30:00Z",
        "updated_at": "2024-01-15T09:30:00Z",
        "api_roles": ["owner"],
        "api_policy": {"name": "name", "allowed_operations": {"allowed_operations": {"allow_any_resource": True}}},
    }
    expected_types: typing.Any = {
        "id": None,
        "email": None,
        "username": None,
        "enabled": None,
        "description": None,
        "created_at": "datetime",
        "updated_at": "datetime",
        "api_roles": ("list", {0: None}),
        "api_policy": {"name": None, "allowed_operations": ("dict", {0: (None, {"allow_any_resource": None})})},
    }
    response = client.users.update(username="username")
    validate_response(response, expected_response, expected_types)

    async_response = await async_client.users.update(username="username")
    validate_response(async_response, expected_response, expected_types)


async def test_reset_password(client: Vectara, async_client: AsyncVectara) -> None:
    # Type ignore to avoid mypy complaining about the function not being meant to return a value
    assert client.users.reset_password(username="username") is None  # type: ignore[func-returns-value]

    assert await async_client.users.reset_password(username="username") is None  # type: ignore[func-returns-value]
