# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.pagination import AsyncPager, SyncPager
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.bad_request_error import BadRequestError
from ..errors.conflict_error import ConflictError
from ..errors.forbidden_error import ForbiddenError
from ..errors.not_found_error import NotFoundError
from ..types.error import Error
from ..types.list_pipelines_response import ListPipelinesResponse
from ..types.pipeline import Pipeline
from ..types.pipeline_key import PipelineKey
from ..types.pipeline_name import PipelineName
from ..types.pipeline_run import PipelineRun
from ..types.pipeline_source import PipelineSource
from ..types.pipeline_status import PipelineStatus
from ..types.pipeline_sync_mode import PipelineSyncMode
from ..types.pipeline_transform import PipelineTransform
from ..types.pipeline_trigger import PipelineTrigger
from ..types.update_pipeline_source import UpdatePipelineSource
from .types.list_pipelines_request_source_type import ListPipelinesRequestSourceType
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawPipelinesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(
        self,
        *,
        source_type: typing.Optional[ListPipelinesRequestSourceType] = None,
        status: typing.Optional[PipelineStatus] = None,
        enabled: typing.Optional[bool] = None,
        filter: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        page_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[Pipeline, ListPipelinesResponse]:
        """
        List all pipelines with optional filtering by source type, status, or enabled state.

        Parameters
        ----------
        source_type : typing.Optional[ListPipelinesRequestSourceType]
            Filter pipelines by source type.

        status : typing.Optional[PipelineStatus]
            Filter pipelines by status.

        enabled : typing.Optional[bool]
            Filter pipelines by enabled state.

        filter : typing.Optional[str]
            A regex filter on pipeline name and description.

        limit : typing.Optional[int]
            The maximum number of pipelines to return.

        page_key : typing.Optional[str]
            Used to retrieve the next page of pipelines after the limit has been reached.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[Pipeline, ListPipelinesResponse]
            List of pipelines.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v2/pipelines",
            base_url=self._client_wrapper.get_environment().default,
            method="GET",
            params={
                "source_type": source_type,
                "status": status,
                "enabled": enabled,
                "filter": filter,
                "limit": limit,
                "page_key": page_key,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _parsed_response = typing.cast(
                    ListPipelinesResponse,
                    parse_obj_as(
                        type_=ListPipelinesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                _items = _parsed_response.pipelines
                _has_next = False
                _get_next = None
                if _parsed_response.metadata is not None:
                    _parsed_next = _parsed_response.metadata.page_key
                    _has_next = _parsed_next is not None and _parsed_next != ""
                    _get_next = lambda: self.list(
                        source_type=source_type,
                        status=status,
                        enabled=enabled,
                        filter=filter,
                        limit=limit,
                        page_key=_parsed_next,
                        request_options=request_options,
                    )
                return SyncPager(has_next=_has_next, items=_items, get_next=_get_next, response=_parsed_response)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create(
        self,
        *,
        name: PipelineName,
        source: PipelineSource,
        trigger: PipelineTrigger,
        transform: PipelineTransform,
        key: typing.Optional[PipelineKey] = OMIT,
        description: typing.Optional[str] = OMIT,
        sync_mode: typing.Optional[PipelineSyncMode] = OMIT,
        enabled: typing.Optional[bool] = OMIT,
        metadata: typing.Optional[typing.Dict[str, str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[Pipeline]:
        """
        Create a new pipeline that continuously ingests data from a source system and sends each record to an agent for processing. A new agent session is created per source record. A pipeline is distinct from an agent schedule (which is a recurring single execution of an agent) and from a connector (which is a bidirectional chat integration like Slack). A pipeline is an automated, one-directional flow of all source data through an agent.

        Parameters
        ----------
        name : PipelineName

        source : PipelineSource

        trigger : PipelineTrigger

        transform : PipelineTransform

        key : typing.Optional[PipelineKey]
            A user-provided key for the pipeline. If omitted, one is auto-generated.

        description : typing.Optional[str]

        sync_mode : typing.Optional[PipelineSyncMode]

        enabled : typing.Optional[bool]

        metadata : typing.Optional[typing.Dict[str, str]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Pipeline]
            The pipeline has been created successfully.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v2/pipelines",
            base_url=self._client_wrapper.get_environment().default,
            method="POST",
            json={
                "key": key,
                "name": name,
                "description": description,
                "source": convert_and_respect_annotation_metadata(
                    object_=source, annotation=PipelineSource, direction="write"
                ),
                "trigger": convert_and_respect_annotation_metadata(
                    object_=trigger, annotation=PipelineTrigger, direction="write"
                ),
                "transform": convert_and_respect_annotation_metadata(
                    object_=transform, annotation=PipelineTransform, direction="write"
                ),
                "sync_mode": sync_mode,
                "enabled": enabled,
                "metadata": metadata,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Pipeline,
                    parse_obj_as(
                        type_=Pipeline,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get(
        self, pipeline_key: PipelineKey, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[Pipeline]:
        """
        Retrieve a pipeline by its key, including its current status, watermark, and configuration.

        Parameters
        ----------
        pipeline_key : PipelineKey
            The unique key of the pipeline.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Pipeline]
            The requested pipeline.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/pipelines/{encode_path_param(pipeline_key)}",
            base_url=self._client_wrapper.get_environment().default,
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Pipeline,
                    parse_obj_as(
                        type_=Pipeline,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def replace(
        self,
        pipeline_key: PipelineKey,
        *,
        name: PipelineName,
        source: PipelineSource,
        trigger: PipelineTrigger,
        transform: PipelineTransform,
        key: typing.Optional[PipelineKey] = OMIT,
        description: typing.Optional[str] = OMIT,
        sync_mode: typing.Optional[PipelineSyncMode] = OMIT,
        enabled: typing.Optional[bool] = OMIT,
        metadata: typing.Optional[typing.Dict[str, str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[Pipeline]:
        """
        Replace a pipeline's configuration. The full pipeline definition must be provided.

        Parameters
        ----------
        pipeline_key : PipelineKey
            The unique key of the pipeline to replace.

        name : PipelineName

        source : PipelineSource

        trigger : PipelineTrigger

        transform : PipelineTransform

        key : typing.Optional[PipelineKey]
            A user-provided key for the pipeline. If omitted, one is auto-generated.

        description : typing.Optional[str]

        sync_mode : typing.Optional[PipelineSyncMode]

        enabled : typing.Optional[bool]

        metadata : typing.Optional[typing.Dict[str, str]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Pipeline]
            The pipeline has been replaced successfully.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/pipelines/{encode_path_param(pipeline_key)}",
            base_url=self._client_wrapper.get_environment().default,
            method="PUT",
            json={
                "key": key,
                "name": name,
                "description": description,
                "source": convert_and_respect_annotation_metadata(
                    object_=source, annotation=PipelineSource, direction="write"
                ),
                "trigger": convert_and_respect_annotation_metadata(
                    object_=trigger, annotation=PipelineTrigger, direction="write"
                ),
                "transform": convert_and_respect_annotation_metadata(
                    object_=transform, annotation=PipelineTransform, direction="write"
                ),
                "sync_mode": sync_mode,
                "enabled": enabled,
                "metadata": metadata,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Pipeline,
                    parse_obj_as(
                        type_=Pipeline,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete(
        self, pipeline_key: PipelineKey, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[None]:
        """
        Permanently delete a pipeline and its run history. This cancels any in-progress runs. Agent sessions created by this pipeline are not deleted.

        Parameters
        ----------
        pipeline_key : PipelineKey
            The unique key of the pipeline to delete.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[None]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/pipelines/{encode_path_param(pipeline_key)}",
            base_url=self._client_wrapper.get_environment().default,
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return HttpResponse(response=_response, data=None)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update(
        self,
        pipeline_key: PipelineKey,
        *,
        name: typing.Optional[PipelineName] = OMIT,
        description: typing.Optional[str] = OMIT,
        source: typing.Optional[UpdatePipelineSource] = OMIT,
        trigger: typing.Optional[PipelineTrigger] = OMIT,
        transform: typing.Optional[PipelineTransform] = OMIT,
        sync_mode: typing.Optional[PipelineSyncMode] = OMIT,
        enabled: typing.Optional[bool] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Optional[str]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[Pipeline]:
        """
        Partially update a pipeline's configuration. Omitted fields are preserved.

        Parameters
        ----------
        pipeline_key : PipelineKey
            The unique key of the pipeline to update.

        name : typing.Optional[PipelineName]

        description : typing.Optional[str]

        source : typing.Optional[UpdatePipelineSource]

        trigger : typing.Optional[PipelineTrigger]

        transform : typing.Optional[PipelineTransform]

        sync_mode : typing.Optional[PipelineSyncMode]

        enabled : typing.Optional[bool]

        metadata : typing.Optional[typing.Dict[str, typing.Optional[str]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Pipeline]
            The pipeline has been updated successfully.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/pipelines/{encode_path_param(pipeline_key)}",
            base_url=self._client_wrapper.get_environment().default,
            method="PATCH",
            json={
                "name": name,
                "description": description,
                "source": convert_and_respect_annotation_metadata(
                    object_=source, annotation=UpdatePipelineSource, direction="write"
                ),
                "trigger": convert_and_respect_annotation_metadata(
                    object_=trigger, annotation=PipelineTrigger, direction="write"
                ),
                "transform": convert_and_respect_annotation_metadata(
                    object_=transform, annotation=PipelineTransform, direction="write"
                ),
                "sync_mode": sync_mode,
                "enabled": enabled,
                "metadata": metadata,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Pipeline,
                    parse_obj_as(
                        type_=Pipeline,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def trigger(
        self, pipeline_key: PipelineKey, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[PipelineRun]:
        """
        Manually trigger a pipeline run outside of the normal schedule. The pipeline will fetch new data from the source and process it through the agent. Returns the created run.

        Parameters
        ----------
        pipeline_key : PipelineKey
            The unique key of the pipeline to trigger.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PipelineRun]
            The pipeline run has been created.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/pipelines/{encode_path_param(pipeline_key)}/trigger",
            base_url=self._client_wrapper.get_environment().default,
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PipelineRun,
                    parse_obj_as(
                        type_=PipelineRun,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawPipelinesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self,
        *,
        source_type: typing.Optional[ListPipelinesRequestSourceType] = None,
        status: typing.Optional[PipelineStatus] = None,
        enabled: typing.Optional[bool] = None,
        filter: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        page_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[Pipeline, ListPipelinesResponse]:
        """
        List all pipelines with optional filtering by source type, status, or enabled state.

        Parameters
        ----------
        source_type : typing.Optional[ListPipelinesRequestSourceType]
            Filter pipelines by source type.

        status : typing.Optional[PipelineStatus]
            Filter pipelines by status.

        enabled : typing.Optional[bool]
            Filter pipelines by enabled state.

        filter : typing.Optional[str]
            A regex filter on pipeline name and description.

        limit : typing.Optional[int]
            The maximum number of pipelines to return.

        page_key : typing.Optional[str]
            Used to retrieve the next page of pipelines after the limit has been reached.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[Pipeline, ListPipelinesResponse]
            List of pipelines.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v2/pipelines",
            base_url=self._client_wrapper.get_environment().default,
            method="GET",
            params={
                "source_type": source_type,
                "status": status,
                "enabled": enabled,
                "filter": filter,
                "limit": limit,
                "page_key": page_key,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _parsed_response = typing.cast(
                    ListPipelinesResponse,
                    parse_obj_as(
                        type_=ListPipelinesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                _items = _parsed_response.pipelines
                _has_next = False
                _get_next = None
                if _parsed_response.metadata is not None:
                    _parsed_next = _parsed_response.metadata.page_key
                    _has_next = _parsed_next is not None and _parsed_next != ""

                    async def _get_next():
                        return await self.list(
                            source_type=source_type,
                            status=status,
                            enabled=enabled,
                            filter=filter,
                            limit=limit,
                            page_key=_parsed_next,
                            request_options=request_options,
                        )

                return AsyncPager(has_next=_has_next, items=_items, get_next=_get_next, response=_parsed_response)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create(
        self,
        *,
        name: PipelineName,
        source: PipelineSource,
        trigger: PipelineTrigger,
        transform: PipelineTransform,
        key: typing.Optional[PipelineKey] = OMIT,
        description: typing.Optional[str] = OMIT,
        sync_mode: typing.Optional[PipelineSyncMode] = OMIT,
        enabled: typing.Optional[bool] = OMIT,
        metadata: typing.Optional[typing.Dict[str, str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[Pipeline]:
        """
        Create a new pipeline that continuously ingests data from a source system and sends each record to an agent for processing. A new agent session is created per source record. A pipeline is distinct from an agent schedule (which is a recurring single execution of an agent) and from a connector (which is a bidirectional chat integration like Slack). A pipeline is an automated, one-directional flow of all source data through an agent.

        Parameters
        ----------
        name : PipelineName

        source : PipelineSource

        trigger : PipelineTrigger

        transform : PipelineTransform

        key : typing.Optional[PipelineKey]
            A user-provided key for the pipeline. If omitted, one is auto-generated.

        description : typing.Optional[str]

        sync_mode : typing.Optional[PipelineSyncMode]

        enabled : typing.Optional[bool]

        metadata : typing.Optional[typing.Dict[str, str]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Pipeline]
            The pipeline has been created successfully.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v2/pipelines",
            base_url=self._client_wrapper.get_environment().default,
            method="POST",
            json={
                "key": key,
                "name": name,
                "description": description,
                "source": convert_and_respect_annotation_metadata(
                    object_=source, annotation=PipelineSource, direction="write"
                ),
                "trigger": convert_and_respect_annotation_metadata(
                    object_=trigger, annotation=PipelineTrigger, direction="write"
                ),
                "transform": convert_and_respect_annotation_metadata(
                    object_=transform, annotation=PipelineTransform, direction="write"
                ),
                "sync_mode": sync_mode,
                "enabled": enabled,
                "metadata": metadata,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Pipeline,
                    parse_obj_as(
                        type_=Pipeline,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get(
        self, pipeline_key: PipelineKey, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[Pipeline]:
        """
        Retrieve a pipeline by its key, including its current status, watermark, and configuration.

        Parameters
        ----------
        pipeline_key : PipelineKey
            The unique key of the pipeline.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Pipeline]
            The requested pipeline.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/pipelines/{encode_path_param(pipeline_key)}",
            base_url=self._client_wrapper.get_environment().default,
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Pipeline,
                    parse_obj_as(
                        type_=Pipeline,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def replace(
        self,
        pipeline_key: PipelineKey,
        *,
        name: PipelineName,
        source: PipelineSource,
        trigger: PipelineTrigger,
        transform: PipelineTransform,
        key: typing.Optional[PipelineKey] = OMIT,
        description: typing.Optional[str] = OMIT,
        sync_mode: typing.Optional[PipelineSyncMode] = OMIT,
        enabled: typing.Optional[bool] = OMIT,
        metadata: typing.Optional[typing.Dict[str, str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[Pipeline]:
        """
        Replace a pipeline's configuration. The full pipeline definition must be provided.

        Parameters
        ----------
        pipeline_key : PipelineKey
            The unique key of the pipeline to replace.

        name : PipelineName

        source : PipelineSource

        trigger : PipelineTrigger

        transform : PipelineTransform

        key : typing.Optional[PipelineKey]
            A user-provided key for the pipeline. If omitted, one is auto-generated.

        description : typing.Optional[str]

        sync_mode : typing.Optional[PipelineSyncMode]

        enabled : typing.Optional[bool]

        metadata : typing.Optional[typing.Dict[str, str]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Pipeline]
            The pipeline has been replaced successfully.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/pipelines/{encode_path_param(pipeline_key)}",
            base_url=self._client_wrapper.get_environment().default,
            method="PUT",
            json={
                "key": key,
                "name": name,
                "description": description,
                "source": convert_and_respect_annotation_metadata(
                    object_=source, annotation=PipelineSource, direction="write"
                ),
                "trigger": convert_and_respect_annotation_metadata(
                    object_=trigger, annotation=PipelineTrigger, direction="write"
                ),
                "transform": convert_and_respect_annotation_metadata(
                    object_=transform, annotation=PipelineTransform, direction="write"
                ),
                "sync_mode": sync_mode,
                "enabled": enabled,
                "metadata": metadata,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Pipeline,
                    parse_obj_as(
                        type_=Pipeline,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete(
        self, pipeline_key: PipelineKey, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[None]:
        """
        Permanently delete a pipeline and its run history. This cancels any in-progress runs. Agent sessions created by this pipeline are not deleted.

        Parameters
        ----------
        pipeline_key : PipelineKey
            The unique key of the pipeline to delete.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[None]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/pipelines/{encode_path_param(pipeline_key)}",
            base_url=self._client_wrapper.get_environment().default,
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return AsyncHttpResponse(response=_response, data=None)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update(
        self,
        pipeline_key: PipelineKey,
        *,
        name: typing.Optional[PipelineName] = OMIT,
        description: typing.Optional[str] = OMIT,
        source: typing.Optional[UpdatePipelineSource] = OMIT,
        trigger: typing.Optional[PipelineTrigger] = OMIT,
        transform: typing.Optional[PipelineTransform] = OMIT,
        sync_mode: typing.Optional[PipelineSyncMode] = OMIT,
        enabled: typing.Optional[bool] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Optional[str]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[Pipeline]:
        """
        Partially update a pipeline's configuration. Omitted fields are preserved.

        Parameters
        ----------
        pipeline_key : PipelineKey
            The unique key of the pipeline to update.

        name : typing.Optional[PipelineName]

        description : typing.Optional[str]

        source : typing.Optional[UpdatePipelineSource]

        trigger : typing.Optional[PipelineTrigger]

        transform : typing.Optional[PipelineTransform]

        sync_mode : typing.Optional[PipelineSyncMode]

        enabled : typing.Optional[bool]

        metadata : typing.Optional[typing.Dict[str, typing.Optional[str]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Pipeline]
            The pipeline has been updated successfully.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/pipelines/{encode_path_param(pipeline_key)}",
            base_url=self._client_wrapper.get_environment().default,
            method="PATCH",
            json={
                "name": name,
                "description": description,
                "source": convert_and_respect_annotation_metadata(
                    object_=source, annotation=UpdatePipelineSource, direction="write"
                ),
                "trigger": convert_and_respect_annotation_metadata(
                    object_=trigger, annotation=PipelineTrigger, direction="write"
                ),
                "transform": convert_and_respect_annotation_metadata(
                    object_=transform, annotation=PipelineTransform, direction="write"
                ),
                "sync_mode": sync_mode,
                "enabled": enabled,
                "metadata": metadata,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Pipeline,
                    parse_obj_as(
                        type_=Pipeline,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def trigger(
        self, pipeline_key: PipelineKey, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[PipelineRun]:
        """
        Manually trigger a pipeline run outside of the normal schedule. The pipeline will fetch new data from the source and process it through the agent. Returns the created run.

        Parameters
        ----------
        pipeline_key : PipelineKey
            The unique key of the pipeline to trigger.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PipelineRun]
            The pipeline run has been created.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/pipelines/{encode_path_param(pipeline_key)}/trigger",
            base_url=self._client_wrapper.get_environment().default,
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PipelineRun,
                    parse_obj_as(
                        type_=PipelineRun,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
