# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.pagination import AsyncPager, SyncPager
from ..core.request_options import RequestOptions
from ..types.agent_key import AgentKey
from ..types.agent_session import AgentSession
from ..types.agent_session_key import AgentSessionKey
from ..types.list_agent_sessions_response import ListAgentSessionsResponse
from .raw_client import AsyncRawAgentSessionsClient, RawAgentSessionsClient
from .types.create_agent_session_request_from_session import CreateAgentSessionRequestFromSession

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class AgentSessionsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAgentSessionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAgentSessionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAgentSessionsClient
        """
        return self._raw_client

    def list(
        self,
        agent_key: AgentKey,
        *,
        filter: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        page_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[AgentSession, ListAgentSessionsResponse]:
        """
        List all agent sessions for the specified agent. This endpoint returns high-level information about each session, with optional filtering and pagination. Use this operation to browse existing sessions or to locate a specific session key for further inspection or updates.

        Parameters
        ----------
        agent_key : AgentKey
            The unique identifier of the agent to list sessions for.

        filter : typing.Optional[str]
            A regular expression against session names and descriptions to filter the results.

        limit : typing.Optional[int]
            The maximum number of sessions to return in the list.

        page_key : typing.Optional[str]
            Used to retrieve the next page of sessions after the limit has been reached.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[AgentSession, ListAgentSessionsResponse]
            List of available agent sessions.

        Examples
        --------
        from vectara import Vectara

        client = Vectara(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        response = client.agent_sessions.list(
            agent_key="customer_support",
            filter="support.*",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list(
            agent_key, filter=filter, limit=limit, page_key=page_key, request_options=request_options
        )

    def create(
        self,
        agent_key: AgentKey,
        *,
        key: typing.Optional[AgentSessionKey] = OMIT,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        enabled: typing.Optional[bool] = OMIT,
        tti_minutes: typing.Optional[int] = OMIT,
        from_session: typing.Optional[CreateAgentSessionRequestFromSession] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AgentSession:
        """
        Create a new session for interacting with an agent. A session is the conversation container that maintains state across all messages, events, tool use, and agent responses.
        
        This endpoint initializes the session and enables you to configure its initial properties, including optional metadata. Metadata can influence agent behavior, personalize responses, or apply access controls. Instructions and tools can also reference metadata using `${\\session.metadata.field}` or `$\\ref` syntax.
        
        A session also serves as the workspace for artifacts, enabling file uploads and multi-step workflows. For more information, see [Working with artifacts in sessions](https://docs.vectara.com/docs/agent-os/sessions#working-with-artifacts-in-sessions).
        
        ## Example request
        
        ```json
        \\$ curl -X POST https://api.vectara.io/v2/agents/support-agent/sessions \\
        -H "Authorization: Bearer YOUR_API_KEY" \\
        -H "Content-Type: application/json" \\
        -d '{
          "key": "user_12345_session",
          "name": "Customer Support Session",
          "metadata": {
            "user_role": "premium",
            "language": "en"
          }
        }'
        ```
        A successful response includes the unique session key, configuration metadata, and timestamps for creation and last update.
        
        Parameters
        ----------
        agent_key : AgentKey
            The unique key of the agent to create a session for.
        
        key : typing.Optional[AgentSessionKey]
            A user provided key that uniquely identifies this session. If not provided, one will be auto-generated based on the session name.
        
        name : typing.Optional[str]
            Human-readable name for the session.
        
        description : typing.Optional[str]
            Optional description of the session purpose or context.
        
        metadata : typing.Optional[typing.Dict[str, typing.Any]]
            Arbitrary metadata associated with the session.
        
        enabled : typing.Optional[bool]
            Whether the session should be enabled upon creation.
        
        tti_minutes : typing.Optional[int]
            Time-to-idle in minutes for the session. If no events occur in the session for this duration, the session will be automatically deleted. If set to 0, the session will not expire.
        
        from_session : typing.Optional[CreateAgentSessionRequestFromSession]
            Create a new session by forking an existing one. By default, copies all visible events
            and artifacts from the source session without compaction. Optionally specify exactly one of
            include_up_to_event_id or compact_up_to_event_id to control which events are included
            and whether they are compacted. These two fields are mutually exclusive.
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        AgentSession
            The response includes the complete session configuration including the unique session key, associated agent key, and creation timestamp.
        
        Examples
        --------
        from vectara import Vectara
        
        client = Vectara(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.agent_sessions.create(
            agent_key="customer_support",
        )
        """
        _response = self._raw_client.create(
            agent_key,
            key=key,
            name=name,
            description=description,
            metadata=metadata,
            enabled=enabled,
            tti_minutes=tti_minutes,
            from_session=from_session,
            request_options=request_options,
        )
        return _response.data

    def get(
        self,
        agent_key: AgentKey,
        session_key: AgentSessionKey,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AgentSession:
        """
        Retrieve the full details of a specific agent session using its unique session key. The response includes the session's configuration, metadata, timestamps, and other stored properties. Use this endpoint to inspect the current state of a session or verify its configuration.

        Parameters
        ----------
        agent_key : AgentKey
            The unique identifier of the agent.

        session_key : AgentSessionKey
            The unique key of the session to retrieve.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentSession
            The requested agent session details.

        Examples
        --------
        from vectara import Vectara

        client = Vectara(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.agent_sessions.get(
            agent_key="customer_support",
            session_key="customer_support_chat",
        )
        """
        _response = self._raw_client.get(agent_key, session_key, request_options=request_options)
        return _response.data

    def delete(
        self,
        agent_key: AgentKey,
        session_key: AgentSessionKey,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Permanently delete an agent session. This action cannot be undone.

        Parameters
        ----------
        agent_key : AgentKey
            The unique identifier of the agent.

        session_key : AgentSessionKey
            The unique key of the session to delete.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from vectara import Vectara

        client = Vectara(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.agent_sessions.delete(
            agent_key="customer_support",
            session_key="customer_support_chat",
        )
        """
        _response = self._raw_client.delete(agent_key, session_key, request_options=request_options)
        return _response.data

    def update(
        self,
        agent_key: AgentKey,
        session_key: AgentSessionKey,
        *,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        enabled: typing.Optional[bool] = OMIT,
        tti_minutes: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AgentSession:
        """
        Update the configuration of an existing agent session. This endpoint enables you to modify fields such as the name, description, or metadata.

        Updated metadata immediately influences agent behavior and becomes available to instructions and tools for the remainder of the session. For more details about configuring the agent session, see [Create agent session](https://docs.vectara.com/docs/rest-api/create-agent-session).

        Parameters
        ----------
        agent_key : AgentKey
            The unique identifier of the agent.

        session_key : AgentSessionKey
            The unique key of the session to update.

        name : typing.Optional[str]
            Human-readable name for the session.

        description : typing.Optional[str]
            Optional description of the session purpose or context.

        metadata : typing.Optional[typing.Dict[str, typing.Any]]
            Arbitrary metadata associated with the session.

        enabled : typing.Optional[bool]
            Whether the session is enabled.

        tti_minutes : typing.Optional[int]
            Time-to-idle in minutes for the session. If no events occur in the session for this duration, the session will be automatically deleted. If set to 0, the session will not expire.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentSession
            The agent session has been updated successfully.

        Examples
        --------
        from vectara import Vectara

        client = Vectara(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.agent_sessions.update(
            agent_key="customer_support",
            session_key="customer_support_chat",
        )
        """
        _response = self._raw_client.update(
            agent_key,
            session_key,
            name=name,
            description=description,
            metadata=metadata,
            enabled=enabled,
            tti_minutes=tti_minutes,
            request_options=request_options,
        )
        return _response.data


class AsyncAgentSessionsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAgentSessionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAgentSessionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAgentSessionsClient
        """
        return self._raw_client

    async def list(
        self,
        agent_key: AgentKey,
        *,
        filter: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        page_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[AgentSession, ListAgentSessionsResponse]:
        """
        List all agent sessions for the specified agent. This endpoint returns high-level information about each session, with optional filtering and pagination. Use this operation to browse existing sessions or to locate a specific session key for further inspection or updates.

        Parameters
        ----------
        agent_key : AgentKey
            The unique identifier of the agent to list sessions for.

        filter : typing.Optional[str]
            A regular expression against session names and descriptions to filter the results.

        limit : typing.Optional[int]
            The maximum number of sessions to return in the list.

        page_key : typing.Optional[str]
            Used to retrieve the next page of sessions after the limit has been reached.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[AgentSession, ListAgentSessionsResponse]
            List of available agent sessions.

        Examples
        --------
        import asyncio

        from vectara import AsyncVectara

        client = AsyncVectara(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            response = await client.agent_sessions.list(
                agent_key="customer_support",
                filter="support.*",
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list(
            agent_key, filter=filter, limit=limit, page_key=page_key, request_options=request_options
        )

    async def create(
        self,
        agent_key: AgentKey,
        *,
        key: typing.Optional[AgentSessionKey] = OMIT,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        enabled: typing.Optional[bool] = OMIT,
        tti_minutes: typing.Optional[int] = OMIT,
        from_session: typing.Optional[CreateAgentSessionRequestFromSession] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AgentSession:
        """
        Create a new session for interacting with an agent. A session is the conversation container that maintains state across all messages, events, tool use, and agent responses.
        
        This endpoint initializes the session and enables you to configure its initial properties, including optional metadata. Metadata can influence agent behavior, personalize responses, or apply access controls. Instructions and tools can also reference metadata using `${\\session.metadata.field}` or `$\\ref` syntax.
        
        A session also serves as the workspace for artifacts, enabling file uploads and multi-step workflows. For more information, see [Working with artifacts in sessions](https://docs.vectara.com/docs/agent-os/sessions#working-with-artifacts-in-sessions).
        
        ## Example request
        
        ```json
        \\$ curl -X POST https://api.vectara.io/v2/agents/support-agent/sessions \\
        -H "Authorization: Bearer YOUR_API_KEY" \\
        -H "Content-Type: application/json" \\
        -d '{
          "key": "user_12345_session",
          "name": "Customer Support Session",
          "metadata": {
            "user_role": "premium",
            "language": "en"
          }
        }'
        ```
        A successful response includes the unique session key, configuration metadata, and timestamps for creation and last update.
        
        Parameters
        ----------
        agent_key : AgentKey
            The unique key of the agent to create a session for.
        
        key : typing.Optional[AgentSessionKey]
            A user provided key that uniquely identifies this session. If not provided, one will be auto-generated based on the session name.
        
        name : typing.Optional[str]
            Human-readable name for the session.
        
        description : typing.Optional[str]
            Optional description of the session purpose or context.
        
        metadata : typing.Optional[typing.Dict[str, typing.Any]]
            Arbitrary metadata associated with the session.
        
        enabled : typing.Optional[bool]
            Whether the session should be enabled upon creation.
        
        tti_minutes : typing.Optional[int]
            Time-to-idle in minutes for the session. If no events occur in the session for this duration, the session will be automatically deleted. If set to 0, the session will not expire.
        
        from_session : typing.Optional[CreateAgentSessionRequestFromSession]
            Create a new session by forking an existing one. By default, copies all visible events
            and artifacts from the source session without compaction. Optionally specify exactly one of
            include_up_to_event_id or compact_up_to_event_id to control which events are included
            and whether they are compacted. These two fields are mutually exclusive.
        
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.
        
        Returns
        -------
        AgentSession
            The response includes the complete session configuration including the unique session key, associated agent key, and creation timestamp.
        
        Examples
        --------
        import asyncio
        
        from vectara import AsyncVectara
        
        client = AsyncVectara(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        
        
        async def main() -> None:
            await client.agent_sessions.create(
                agent_key="customer_support",
            )
        
        
        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            agent_key,
            key=key,
            name=name,
            description=description,
            metadata=metadata,
            enabled=enabled,
            tti_minutes=tti_minutes,
            from_session=from_session,
            request_options=request_options,
        )
        return _response.data

    async def get(
        self,
        agent_key: AgentKey,
        session_key: AgentSessionKey,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AgentSession:
        """
        Retrieve the full details of a specific agent session using its unique session key. The response includes the session's configuration, metadata, timestamps, and other stored properties. Use this endpoint to inspect the current state of a session or verify its configuration.

        Parameters
        ----------
        agent_key : AgentKey
            The unique identifier of the agent.

        session_key : AgentSessionKey
            The unique key of the session to retrieve.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentSession
            The requested agent session details.

        Examples
        --------
        import asyncio

        from vectara import AsyncVectara

        client = AsyncVectara(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.agent_sessions.get(
                agent_key="customer_support",
                session_key="customer_support_chat",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(agent_key, session_key, request_options=request_options)
        return _response.data

    async def delete(
        self,
        agent_key: AgentKey,
        session_key: AgentSessionKey,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Permanently delete an agent session. This action cannot be undone.

        Parameters
        ----------
        agent_key : AgentKey
            The unique identifier of the agent.

        session_key : AgentSessionKey
            The unique key of the session to delete.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from vectara import AsyncVectara

        client = AsyncVectara(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.agent_sessions.delete(
                agent_key="customer_support",
                session_key="customer_support_chat",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(agent_key, session_key, request_options=request_options)
        return _response.data

    async def update(
        self,
        agent_key: AgentKey,
        session_key: AgentSessionKey,
        *,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        enabled: typing.Optional[bool] = OMIT,
        tti_minutes: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AgentSession:
        """
        Update the configuration of an existing agent session. This endpoint enables you to modify fields such as the name, description, or metadata.

        Updated metadata immediately influences agent behavior and becomes available to instructions and tools for the remainder of the session. For more details about configuring the agent session, see [Create agent session](https://docs.vectara.com/docs/rest-api/create-agent-session).

        Parameters
        ----------
        agent_key : AgentKey
            The unique identifier of the agent.

        session_key : AgentSessionKey
            The unique key of the session to update.

        name : typing.Optional[str]
            Human-readable name for the session.

        description : typing.Optional[str]
            Optional description of the session purpose or context.

        metadata : typing.Optional[typing.Dict[str, typing.Any]]
            Arbitrary metadata associated with the session.

        enabled : typing.Optional[bool]
            Whether the session is enabled.

        tti_minutes : typing.Optional[int]
            Time-to-idle in minutes for the session. If no events occur in the session for this duration, the session will be automatically deleted. If set to 0, the session will not expire.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentSession
            The agent session has been updated successfully.

        Examples
        --------
        import asyncio

        from vectara import AsyncVectara

        client = AsyncVectara(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.agent_sessions.update(
                agent_key="customer_support",
                session_key="customer_support_chat",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            agent_key,
            session_key,
            name=name,
            description=description,
            metadata=metadata,
            enabled=enabled,
            tti_minutes=tti_minutes,
            request_options=request_options,
        )
        return _response.data
