# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.pydantic_utilities import pydantic_v1
from ..core.request_options import RequestOptions
from ..errors.forbidden_error import ForbiddenError
from ..types.error import Error
from ..types.list_rerankers_response import ListRerankersResponse


class RerankersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(
        self,
        *,
        filter: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        page_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None
    ) -> ListRerankersResponse:
        """
        Rerankers are used to improve the ranking (ordering) of search results.

        Parameters
        ----------
        filter : typing.Optional[str]
            A regular expression against reranker names and descriptions.

        limit : typing.Optional[int]
            The maximum number of rerankers to return in the list.

        page_key : typing.Optional[str]
            Used to the retrieve the next page of rerankers after the limit has been reached.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListRerankersResponse
            List of rerankers.

        Examples
        --------
        from vectara.client import Vectara

        client = Vectara(
            api_key="YOUR_API_KEY",
        )
        client.rerankers.list(
            filter="vectara.*",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            "v2/rerankers",
            base_url=self._client_wrapper.get_environment().default,
            method="GET",
            params={"filter": filter, "limit": limit, "page_key": page_key},
            request_options=request_options,
        )
        if 200 <= _response.status_code < 300:
            return pydantic_v1.parse_obj_as(ListRerankersResponse, _response.json())  # type: ignore
        if _response.status_code == 403:
            raise ForbiddenError(pydantic_v1.parse_obj_as(Error, _response.json()))  # type: ignore
        try:
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)


class AsyncRerankersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self,
        *,
        filter: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        page_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None
    ) -> ListRerankersResponse:
        """
        Rerankers are used to improve the ranking (ordering) of search results.

        Parameters
        ----------
        filter : typing.Optional[str]
            A regular expression against reranker names and descriptions.

        limit : typing.Optional[int]
            The maximum number of rerankers to return in the list.

        page_key : typing.Optional[str]
            Used to the retrieve the next page of rerankers after the limit has been reached.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListRerankersResponse
            List of rerankers.

        Examples
        --------
        from vectara.client import AsyncVectara

        client = AsyncVectara(
            api_key="YOUR_API_KEY",
        )
        await client.rerankers.list(
            filter="vectara.*",
        )
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v2/rerankers",
            base_url=self._client_wrapper.get_environment().default,
            method="GET",
            params={"filter": filter, "limit": limit, "page_key": page_key},
            request_options=request_options,
        )
        if 200 <= _response.status_code < 300:
            return pydantic_v1.parse_obj_as(ListRerankersResponse, _response.json())  # type: ignore
        if _response.status_code == 403:
            raise ForbiddenError(pydantic_v1.parse_obj_as(Error, _response.json()))  # type: ignore
        try:
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)
