# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .agent_key import AgentKey
from .pipeline_verification import PipelineVerification


class AgentTransformConfiguration(UniversalBaseModel):
    """
    Process source data using an agent. Each run creates one or more agent sessions
    and sends source records as input for the agent to act on per its instructions.
    """

    agent_key: AgentKey
    verification: typing.Optional[PipelineVerification] = pydantic.Field(default=None)
    """
    Optional verification strategy to determine whether a record was successfully
    processed. If omitted, any non-exception agent completion counts as success.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
