# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .agent_input import AgentInput
from .agent_session_key import AgentSessionKey
from .artifact_reference import ArtifactReference
from .image_read_event_detail import ImageReadEventDetail


class AgentEvent_InputMessage(UniversalBaseModel):
    """
    An event in an agent session conversation.
    """

    type: typing.Literal["input_message"] = "input_message"
    messages: typing.List[AgentInput]
    id: str
    session_key: AgentSessionKey
    created_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class AgentEvent_SkillLoad(UniversalBaseModel):
    """
    An event in an agent session conversation.
    """

    type: typing.Literal["skill_load"] = "skill_load"
    skill_name: str
    content: str
    id: str
    session_key: AgentSessionKey
    created_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class AgentEvent_ArtifactUpload(UniversalBaseModel):
    """
    An event in an agent session conversation.
    """

    type: typing.Literal["artifact_upload"] = "artifact_upload"
    artifacts: typing.List[ArtifactReference]
    id: str
    session_key: AgentSessionKey
    created_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class AgentEvent_ToolInput(UniversalBaseModel):
    """
    An event in an agent session conversation.
    """

    type: typing.Literal["tool_input"] = "tool_input"
    tool_call_id: str
    tool_configuration_name: str
    tool_name: str
    tool_input: typing.Dict[str, typing.Any]
    id: str
    session_key: AgentSessionKey
    created_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class AgentEvent_ToolOutput(UniversalBaseModel):
    """
    An event in an agent session conversation.
    """

    type: typing.Literal["tool_output"] = "tool_output"
    tool_call_id: str
    tool_configuration_name: str
    tool_name: str
    tool_output: typing.Dict[str, typing.Any]
    error: bool
    id: str
    session_key: AgentSessionKey
    created_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class AgentEvent_Thinking(UniversalBaseModel):
    """
    An event in an agent session conversation.
    """

    type: typing.Literal["thinking"] = "thinking"
    content: typing.Optional[str] = None
    id: str
    session_key: AgentSessionKey
    created_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class AgentEvent_AgentOutput(UniversalBaseModel):
    """
    An event in an agent session conversation.
    """

    type: typing.Literal["agent_output"] = "agent_output"
    content: str
    id: str
    session_key: AgentSessionKey
    created_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class AgentEvent_StructuredOutput(UniversalBaseModel):
    """
    An event in an agent session conversation.
    """

    type: typing.Literal["structured_output"] = "structured_output"
    schema_name: str
    content: typing.Any
    id: str
    session_key: AgentSessionKey
    created_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class AgentEvent_ContextLimitExceeded(UniversalBaseModel):
    """
    An event in an agent session conversation.
    """

    type: typing.Literal["context_limit_exceeded"] = "context_limit_exceeded"
    context_limit: typing.Optional[int] = None
    actual_tokens: typing.Optional[int] = None
    message: str
    id: str
    session_key: AgentSessionKey
    created_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class AgentEvent_StepTransitionLimitExceeded(UniversalBaseModel):
    """
    An event in an agent session conversation.
    """

    type: typing.Literal["step_transition_limit_exceeded"] = "step_transition_limit_exceeded"
    transition_limit: typing.Optional[int] = None
    message: str
    id: str
    session_key: AgentSessionKey
    created_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class AgentEvent_SessionInterrupted(UniversalBaseModel):
    """
    An event in an agent session conversation.
    """

    type: typing.Literal["session_interrupted"] = "session_interrupted"
    id: str
    session_key: AgentSessionKey
    created_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class AgentEvent_ImageRead(UniversalBaseModel):
    """
    An event in an agent session conversation.
    """

    type: typing.Literal["image_read"] = "image_read"
    artifact_id: str
    detail: typing.Optional[ImageReadEventDetail] = None
    id: str
    session_key: AgentSessionKey
    created_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class AgentEvent_StepTransition(UniversalBaseModel):
    """
    An event in an agent session conversation.
    """

    type: typing.Literal["step_transition"] = "step_transition"
    from_step: str
    to_step: str
    content: str
    id: str
    session_key: AgentSessionKey
    created_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class AgentEvent_Compaction(UniversalBaseModel):
    """
    An event in an agent session conversation.
    """

    type: typing.Literal["compaction"] = "compaction"
    turns_compacted: int
    events_compacted: int
    summary_text: typing.Optional[str] = None
    summary_key: str
    id: str
    session_key: AgentSessionKey
    created_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


AgentEvent = typing_extensions.Annotated[
    typing.Union[
        AgentEvent_InputMessage,
        AgentEvent_SkillLoad,
        AgentEvent_ArtifactUpload,
        AgentEvent_ToolInput,
        AgentEvent_ToolOutput,
        AgentEvent_Thinking,
        AgentEvent_AgentOutput,
        AgentEvent_StructuredOutput,
        AgentEvent_ContextLimitExceeded,
        AgentEvent_StepTransitionLimitExceeded,
        AgentEvent_SessionInterrupted,
        AgentEvent_ImageRead,
        AgentEvent_StepTransition,
        AgentEvent_Compaction,
    ],
    pydantic.Field(discriminator="type"),
]
