# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs
from .agent_output_parser import AgentOutputParser
from .agent_step_instruction import AgentStepInstruction
from .agent_step_reminder import AgentStepReminder
from .next_step import NextStep


class AgentStep(UniversalBaseModel):
    """
    A step in an agent's execution flow that defines how the agent processes and responds to input.
    The step name comes from the map key in the agent's steps map.

    A step gets all previous session history in the agent session, including any prior agent steps,
    then the agent decides what to do in this step based on the given instructions. Finally, the
    agent either stops working if there is no next step defined or continues to the first next step
    that matches the condition.

    An agent always executes steps serially. If parallel behavior is desired, giving the agent
    other agents as tools is usually the most correct approach.

    Each step can only use tools defined by its `allowed_tools` list; if this list is not specified
    then all tools known to the agent are allowed.
    """

    type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Deprecated. This field is ignored and exists only for backward compatibility.
    """

    instructions: typing.List[AgentStepInstruction] = pydantic.Field()
    """
    List of instructions that guide the agent's behavior in this step.
    If omitted, the agent may behave oddly as it has no system instructions and
    will just attempt to respond to user input and previous session history.
    """

    output_parser: AgentOutputParser = pydantic.Field()
    """
    How to parse and format the agent's output.
    Determines which event type is emitted.
    Defaults to 'default' parser if not specified.
    """

    reminders: typing.Optional[typing.List[AgentStepReminder]] = pydantic.Field(default=None)
    """
    Reminders injected into conversation messages when specific events occur. Useful for keeping the agent on-task during long conversations.
    """

    next_steps: typing.Optional[typing.List[NextStep]] = pydantic.Field(default=None)
    """
    Conditional transitions to other steps.
    Evaluated in order; first matching condition is selected.
    A next_step without a condition acts as a catch-all/default.
    If no condition matches, the agent remains on the current step and the agent ends output.
    """

    allowed_tools: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    List of tool configuration names that this step is allowed to use.
    If not specified (null), all tools defined in the agent's tool_configurations are allowed.
    If set to an empty array, no tools are allowed and the agent can only respond with text.
    Tool names must reference keys in the agent's tool_configurations map.
    """

    allowed_skills: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    List of skill names that this step is allowed to use.
    If not specified (null), all skills defined in the agent's skills map are allowed.
    If set to an empty array, no skills are available and the invoke_skill tool is not shown.
    """

    reentry_step: typing.Optional[str] = pydantic.Field(default=None)
    """
    Step name to resume at when the session receives the next user message.
    If not specified, the session re-enters at this step (i.e., stays here).
    Set to the agent's first_step_name to always restart from the beginning.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


update_forward_refs(AgentStep)
