# This file was auto-generated by Fern from our API Definition.

import typing

CustomDimensions = typing.Optional[typing.Dict[str, typing.Optional[float]]]
"""
The custom dimensions as additional weights.
"""
