# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic.v1 as pydantic

from ..core.datetime_utils import serialize_datetime
from ..core.pydantic_utilities import deep_union_pydantic_dicts


class Encoder(pydantic.BaseModel):
    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The Encoder ID.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The encoder name.
    """

    output_dimensions: typing.Optional[int] = pydantic.Field(default=None)
    """
    When this encoder is used to create an embedding, it shows the count of dimensions for the output embedding.
    A high dimensionality will consume more storage space, but it allows for an increase the quality of
    the embedding.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    The encoder description.
    """

    default: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Indicates whether the encoder is default used when creating a corpus.
    """

    enabled: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Indicates whether the encoder is enabled.
    """

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults_exclude_unset: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        kwargs_with_defaults_exclude_none: typing.Any = {"by_alias": True, "exclude_none": True, **kwargs}

        return deep_union_pydantic_dicts(
            super().dict(**kwargs_with_defaults_exclude_unset), super().dict(**kwargs_with_defaults_exclude_none)
        )

    class Config:
        frozen = True
        smart_union = True
        extra = pydantic.Extra.allow
        json_encoders = {dt.datetime: serialize_datetime}
