# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .reranker import Reranker
import pydantic
from .list_metadata import ListMetadata
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class ListRerankersResponse(UniversalBaseModel):
    rerankers: typing.Optional[typing.List[Reranker]] = pydantic.Field(default=None)
    """
    An array of rerankers.
    """

    metadata: typing.Optional[ListMetadata] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
