# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .list_metadata import ListMetadata
from .pipeline import Pipeline


class ListPipelinesResponse(UniversalBaseModel):
    """
    Response containing a list of pipelines.
    """

    pipelines: typing.List[Pipeline]
    metadata: ListMetadata

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
