# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class McpToolAnnotations(UniversalBaseModel):
    """
    Optional hints about tool behaviour/metadata.
    """

    read_only_hint: typing.Optional[bool] = pydantic.Field(default=None)
    """
    If true, the tool does not modify its environment.
    """

    destructive_hint: typing.Optional[bool] = pydantic.Field(default=None)
    """
    If true, the tool may perform destructive updates.
    """

    idempotent_hint: typing.Optional[bool] = pydantic.Field(default=None)
    """
    If true, repeated calls with same args have no additional effect.
    """

    open_world_hint: typing.Optional[bool] = pydantic.Field(default=None)
    """
    If true, tool interacts with external entities.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
