# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class NextStep(UniversalBaseModel):
    """
    A conditional transition to another step.
    """

    condition: typing.Optional[str] = pydantic.Field(default=None)
    """
    UserFn expression evaluating to boolean.
    Uses the `get()` function with JSONPath to access the step transition context.
    See https://docs.vectara.com/docs/search-and-retrieval/rerankers/user-defined-function-reranker for the UserFn language reference.
    Omit for catch-all/default routing.
    
    The context available to `get()` has the following shape:
    ```
    {
      "agent": {
        "name": "...",
        "key": "...",
        "description": "...",
        "metadata": { ... }
      },
      "session": {
        "key": "...",
        "name": "...",
        "description": "...",
        "metadata": { ... }
      },
      "currentDate": "2024-01-15T10:35:00Z",
      "tools": {
        "<tool_config_name>": {
          "outputs": {
            "latest": { ... }
          }
        }
      },
      "output": { "text": "..." }
    }
    ```
    
    - `$.agent.metadata.<key>` — agent metadata fields
    - `$.session.metadata.<key>` — session metadata fields
    - `$.tools.<tool_config_name>.outputs.latest.<field>` — latest tool output fields
    - `$.output.text` — LLM text output (when output_parser is `default`)
    - `$.output.<field>` — LLM structured output fields (when output_parser is `structured`)
    """

    step_name: str = pydantic.Field()
    """
    Name of the step to transition to.
    Must reference a step defined in the agent's steps list.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
