# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class PipelineSource_S3(UniversalBaseModel):
    """
    The source system to ingest data from.
    """

    type: typing.Literal["s3"] = "s3"
    bucket: typing.Optional[str] = None
    prefix: typing.Optional[str] = None
    region: typing.Optional[str] = None
    endpoint_url: typing.Optional[str] = None
    access_key_id: typing.Optional[str] = None
    secret_access_key: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


PipelineSource = PipelineSource_S3
