# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs
from .generation_parameters import GenerationParameters
from .search_corpora_parameters import SearchCorporaParameters


class QueryRequest(UniversalBaseModel):
    """
    Query one or more corpora.
    """

    query: str = pydantic.Field()
    """
    The search query string, which is the question the user is asking.
    """

    search: SearchCorporaParameters
    generation: typing.Optional[GenerationParameters] = None
    stream_response: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Indicates whether the response should be streamed or not.
    """

    save_history: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Indicates whether to save the query to query history.
    """

    intelligent_query_rewriting: typing.Optional[bool] = pydantic.Field(default=None)
    """
    [Tech Preview] Indicates whether to enable intelligent query rewriting. When enabled, the platform will attempt to extract metadata filter and rewrite the query to improve search results. Read [here](https://docs.vectara.com/docs/search-and-retrieval/intelligent-query-rewriting) for more details.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


update_forward_refs(QueryRequest)
