# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .test_lambda_tool_response_validation_status import TestLambdaToolResponseValidationStatus


class TestLambdaToolResponseValidation(UniversalBaseModel):
    """
    Results of code validation (static and sandbox).
    """

    status: TestLambdaToolResponseValidationStatus = pydantic.Field()
    """
    Overall validation status.
    """

    errors: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    List of validation errors if the code is invalid.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
