# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from .agent_event_base import AgentEventBase


class ThinkingEvent(AgentEventBase):
    """
    An event representing chain-of-thought thinking by the agent.
    """

    content: typing.Optional[str] = pydantic.Field(default=None)
    """
    Human-readable content of the reasoning process.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
