# This file was auto-generated by Fern from our API Definition.

import typing

from .corpora_search_tool import CorporaSearchTool
from .lambda_tool import LambdaTool
from .mcp_tool import McpTool
from .structured_indexing_tool import StructuredIndexingTool
from .web_search_tool import WebSearchTool

Tool = typing.Union[McpTool, CorporaSearchTool, WebSearchTool, LambdaTool, StructuredIndexingTool]
