# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .function_definition import FunctionDefinition
from .lambda_tool_language import LambdaToolLanguage
from .mcp_tool_annotations import McpToolAnnotations
from .tool_description_template import ToolDescriptionTemplate
from .tool_id import ToolId
from .tool_server_id import ToolServerId


class Tool_DynamicVectara(UniversalBaseModel):
    """
    A tool that can be used by agents to perform specific actions or operations.
    """

    type: typing.Literal["dynamic_vectara"] = "dynamic_vectara"
    id: ToolId
    name: str
    title: typing.Optional[str] = None
    description: str
    description_template: typing.Optional[ToolDescriptionTemplate] = None
    documentation: typing.Optional[str] = None
    enabled: bool
    experimental: typing.Optional[bool] = None
    created_at: typing.Optional[dt.datetime] = None
    updated_at: typing.Optional[dt.datetime] = None
    input_schema: typing.Dict[str, typing.Any]
    category: typing.Optional[str] = None
    lineage: typing.Optional[str] = None
    version: typing.Optional[str] = None
    tool_groups: typing.Optional[typing.List[str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class Tool_Mcp(UniversalBaseModel):
    """
    A tool that can be used by agents to perform specific actions or operations.
    """

    type: typing.Literal["mcp"] = "mcp"
    server_id: typing.Optional[ToolServerId] = None
    annotations: typing.Optional[McpToolAnnotations] = None
    id: ToolId
    name: str
    title: typing.Optional[str] = None
    description: str
    description_template: typing.Optional[ToolDescriptionTemplate] = None
    documentation: typing.Optional[str] = None
    enabled: bool
    experimental: typing.Optional[bool] = None
    created_at: typing.Optional[dt.datetime] = None
    updated_at: typing.Optional[dt.datetime] = None
    input_schema: typing.Dict[str, typing.Any]
    category: typing.Optional[str] = None
    lineage: typing.Optional[str] = None
    version: typing.Optional[str] = None
    tool_groups: typing.Optional[typing.List[str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class Tool_CorporaSearch(UniversalBaseModel):
    """
    A tool that can be used by agents to perform specific actions or operations.
    """

    type: typing.Literal["corpora_search"] = "corpora_search"
    id: ToolId
    name: str
    title: typing.Optional[str] = None
    description: str
    description_template: typing.Optional[ToolDescriptionTemplate] = None
    documentation: typing.Optional[str] = None
    enabled: bool
    experimental: typing.Optional[bool] = None
    created_at: typing.Optional[dt.datetime] = None
    updated_at: typing.Optional[dt.datetime] = None
    input_schema: typing.Dict[str, typing.Any]
    category: typing.Optional[str] = None
    lineage: typing.Optional[str] = None
    version: typing.Optional[str] = None
    tool_groups: typing.Optional[typing.List[str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class Tool_WebSearch(UniversalBaseModel):
    """
    A tool that can be used by agents to perform specific actions or operations.
    """

    type: typing.Literal["web_search"] = "web_search"
    id: ToolId
    name: str
    title: typing.Optional[str] = None
    description: str
    description_template: typing.Optional[ToolDescriptionTemplate] = None
    documentation: typing.Optional[str] = None
    enabled: bool
    experimental: typing.Optional[bool] = None
    created_at: typing.Optional[dt.datetime] = None
    updated_at: typing.Optional[dt.datetime] = None
    input_schema: typing.Dict[str, typing.Any]
    category: typing.Optional[str] = None
    lineage: typing.Optional[str] = None
    version: typing.Optional[str] = None
    tool_groups: typing.Optional[typing.List[str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class Tool_WebGet(UniversalBaseModel):
    """
    A tool that can be used by agents to perform specific actions or operations.
    """

    type: typing.Literal["web_get"] = "web_get"
    id: ToolId
    name: str
    title: typing.Optional[str] = None
    description: str
    description_template: typing.Optional[ToolDescriptionTemplate] = None
    documentation: typing.Optional[str] = None
    enabled: bool
    experimental: typing.Optional[bool] = None
    created_at: typing.Optional[dt.datetime] = None
    updated_at: typing.Optional[dt.datetime] = None
    input_schema: typing.Dict[str, typing.Any]
    category: typing.Optional[str] = None
    lineage: typing.Optional[str] = None
    version: typing.Optional[str] = None
    tool_groups: typing.Optional[typing.List[str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class Tool_Lambda(UniversalBaseModel):
    """
    A tool that can be used by agents to perform specific actions or operations.
    """

    type: typing.Literal["lambda"] = "lambda"
    language: LambdaToolLanguage
    output_schema: typing.Optional[typing.Dict[str, typing.Any]] = None
    function_definition: FunctionDefinition
    id: ToolId
    name: str
    title: typing.Optional[str] = None
    description: str
    description_template: typing.Optional[ToolDescriptionTemplate] = None
    documentation: typing.Optional[str] = None
    enabled: bool
    experimental: typing.Optional[bool] = None
    created_at: typing.Optional[dt.datetime] = None
    updated_at: typing.Optional[dt.datetime] = None
    input_schema: typing.Dict[str, typing.Any]
    category: typing.Optional[str] = None
    lineage: typing.Optional[str] = None
    version: typing.Optional[str] = None
    tool_groups: typing.Optional[typing.List[str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class Tool_SubAgent(UniversalBaseModel):
    """
    A tool that can be used by agents to perform specific actions or operations.
    """

    type: typing.Literal["sub_agent"] = "sub_agent"
    id: ToolId
    name: str
    title: typing.Optional[str] = None
    description: str
    description_template: typing.Optional[ToolDescriptionTemplate] = None
    documentation: typing.Optional[str] = None
    enabled: bool
    experimental: typing.Optional[bool] = None
    created_at: typing.Optional[dt.datetime] = None
    updated_at: typing.Optional[dt.datetime] = None
    input_schema: typing.Dict[str, typing.Any]
    category: typing.Optional[str] = None
    lineage: typing.Optional[str] = None
    version: typing.Optional[str] = None
    tool_groups: typing.Optional[typing.List[str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class Tool_ArtifactCreate(UniversalBaseModel):
    """
    A tool that can be used by agents to perform specific actions or operations.
    """

    type: typing.Literal["artifact_create"] = "artifact_create"
    id: ToolId
    name: str
    title: typing.Optional[str] = None
    description: str
    description_template: typing.Optional[ToolDescriptionTemplate] = None
    documentation: typing.Optional[str] = None
    enabled: bool
    experimental: typing.Optional[bool] = None
    created_at: typing.Optional[dt.datetime] = None
    updated_at: typing.Optional[dt.datetime] = None
    input_schema: typing.Dict[str, typing.Any]
    category: typing.Optional[str] = None
    lineage: typing.Optional[str] = None
    version: typing.Optional[str] = None
    tool_groups: typing.Optional[typing.List[str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class Tool_ArtifactRead(UniversalBaseModel):
    """
    A tool that can be used by agents to perform specific actions or operations.
    """

    type: typing.Literal["artifact_read"] = "artifact_read"
    id: ToolId
    name: str
    title: typing.Optional[str] = None
    description: str
    description_template: typing.Optional[ToolDescriptionTemplate] = None
    documentation: typing.Optional[str] = None
    enabled: bool
    experimental: typing.Optional[bool] = None
    created_at: typing.Optional[dt.datetime] = None
    updated_at: typing.Optional[dt.datetime] = None
    input_schema: typing.Dict[str, typing.Any]
    category: typing.Optional[str] = None
    lineage: typing.Optional[str] = None
    version: typing.Optional[str] = None
    tool_groups: typing.Optional[typing.List[str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class Tool_ArtifactGrep(UniversalBaseModel):
    """
    A tool that can be used by agents to perform specific actions or operations.
    """

    type: typing.Literal["artifact_grep"] = "artifact_grep"
    id: ToolId
    name: str
    title: typing.Optional[str] = None
    description: str
    description_template: typing.Optional[ToolDescriptionTemplate] = None
    documentation: typing.Optional[str] = None
    enabled: bool
    experimental: typing.Optional[bool] = None
    created_at: typing.Optional[dt.datetime] = None
    updated_at: typing.Optional[dt.datetime] = None
    input_schema: typing.Dict[str, typing.Any]
    category: typing.Optional[str] = None
    lineage: typing.Optional[str] = None
    version: typing.Optional[str] = None
    tool_groups: typing.Optional[typing.List[str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class Tool_ImageRead(UniversalBaseModel):
    """
    A tool that can be used by agents to perform specific actions or operations.
    """

    type: typing.Literal["image_read"] = "image_read"
    id: ToolId
    name: str
    title: typing.Optional[str] = None
    description: str
    description_template: typing.Optional[ToolDescriptionTemplate] = None
    documentation: typing.Optional[str] = None
    enabled: bool
    experimental: typing.Optional[bool] = None
    created_at: typing.Optional[dt.datetime] = None
    updated_at: typing.Optional[dt.datetime] = None
    input_schema: typing.Dict[str, typing.Any]
    category: typing.Optional[str] = None
    lineage: typing.Optional[str] = None
    version: typing.Optional[str] = None
    tool_groups: typing.Optional[typing.List[str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class Tool_DocumentConversion(UniversalBaseModel):
    """
    A tool that can be used by agents to perform specific actions or operations.
    """

    type: typing.Literal["document_conversion"] = "document_conversion"
    id: ToolId
    name: str
    title: typing.Optional[str] = None
    description: str
    description_template: typing.Optional[ToolDescriptionTemplate] = None
    documentation: typing.Optional[str] = None
    enabled: bool
    experimental: typing.Optional[bool] = None
    created_at: typing.Optional[dt.datetime] = None
    updated_at: typing.Optional[dt.datetime] = None
    input_schema: typing.Dict[str, typing.Any]
    category: typing.Optional[str] = None
    lineage: typing.Optional[str] = None
    version: typing.Optional[str] = None
    tool_groups: typing.Optional[typing.List[str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class Tool_GetDocumentText(UniversalBaseModel):
    """
    A tool that can be used by agents to perform specific actions or operations.
    """

    type: typing.Literal["get_document_text"] = "get_document_text"
    id: ToolId
    name: str
    title: typing.Optional[str] = None
    description: str
    description_template: typing.Optional[ToolDescriptionTemplate] = None
    documentation: typing.Optional[str] = None
    enabled: bool
    experimental: typing.Optional[bool] = None
    created_at: typing.Optional[dt.datetime] = None
    updated_at: typing.Optional[dt.datetime] = None
    input_schema: typing.Dict[str, typing.Any]
    category: typing.Optional[str] = None
    lineage: typing.Optional[str] = None
    version: typing.Optional[str] = None
    tool_groups: typing.Optional[typing.List[str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


Tool = typing_extensions.Annotated[
    typing.Union[
        Tool_DynamicVectara,
        Tool_Mcp,
        Tool_CorporaSearch,
        Tool_WebSearch,
        Tool_WebGet,
        Tool_Lambda,
        Tool_SubAgent,
        Tool_ArtifactCreate,
        Tool_ArtifactRead,
        Tool_ArtifactGrep,
        Tool_ImageRead,
        Tool_DocumentConversion,
        Tool_GetDocumentText,
    ],
    pydantic.Field(discriminator="type"),
]
