# This file was auto-generated by Fern from our API Definition.

import typing

from .update_lambda_tool_request import UpdateLambdaToolRequest
from .update_mcp_tool_request import UpdateMcpToolRequest

UpdateToolRequest = typing.Union[UpdateMcpToolRequest, UpdateLambdaToolRequest]
