# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class VertexAccessTokenAuth(UniversalBaseModel):
    """
    Google Cloud Vertex AI access token authentication
    """

    access_token: str = pydantic.Field()
    """
    The GCP access token
    """

    project: str = pydantic.Field()
    """
    GCP project ID
    """

    region: str = pydantic.Field()
    """
    GCP region for Vertex AI
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
