# This file was auto-generated by Fern from our API Definition.

import typing

from .vertex_ai_api_key_auth import VertexAiApiKeyAuth
from .vertex_ai_service_account_auth import VertexAiServiceAccountAuth

VertexAiAuth = typing.Union[VertexAiApiKeyAuth, VertexAiServiceAccountAuth]
