# This file was auto-generated by Fern from our API Definition.

import typing

from .eager_reference import EagerReference

WebGetToolParametersHeaders = typing.Union[typing.Dict[str, str], EagerReference]
