# This file was auto-generated by Fern from our API Definition.

import typing

from ...types.context_limit_exceeded_event import ContextLimitExceededEvent
from ...types.stream_error import StreamError
from ...types.stream_response_end import StreamResponseEnd
from ...types.streaming_agent_output import StreamingAgentOutput
from ...types.streaming_agent_output_end import StreamingAgentOutputEnd
from ...types.streaming_thinking import StreamingThinking
from ...types.streaming_thinking_end import StreamingThinkingEnd
from ...types.tool_input_event import ToolInputEvent
from ...types.tool_output_event import ToolOutputEvent

AgentEventsCreateStreamResponse = typing.Union[
    StreamingAgentOutput,
    StreamingAgentOutputEnd,
    StreamingThinking,
    StreamingThinkingEnd,
    ToolInputEvent,
    ToolOutputEvent,
    ContextLimitExceededEvent,
    StreamError,
    StreamResponseEnd,
]
