# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.pagination import AsyncPager, SyncPager
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.bad_request_error import BadRequestError
from ..errors.forbidden_error import ForbiddenError
from ..types.error import Error
from ..types.hallucination_correction_response import HallucinationCorrectionResponse
from ..types.hallucination_corrector import HallucinationCorrector
from ..types.hcm_source_document import HcmSourceDocument
from ..types.list_hallucination_correctors_response import ListHallucinationCorrectorsResponse
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawHallucinationCorrectorsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(
        self,
        *,
        filter: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        page_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[HallucinationCorrector, ListHallucinationCorrectorsResponse]:
        """
        The List Hallucination Correctors API enables users to list available hallucination correctors used for detecting and correcting hallucinations in AI-generated content. Vectara provides these models as part of its broader hallucination evaluation framework, and the Hallucination Correctors endpoint uses these models to propose factual corrections to summaries and other generative outputs.

        Use this API to inspect available correctors, filter results, and determine which hallucination corrector to reference in downstream workflows or evaluation pipelines.

        Parameters
        ----------
        filter : typing.Optional[str]
            A regular expression applied to the name and description fields. Use this to return only hallucination correctors that match specific keywords or naming conventions.

        limit : typing.Optional[int]
            The maximum number of hallucination correctors to return in the list. Defaults to 10. Range is between 1 and 100.

        page_key : typing.Optional[str]
            Retrieves the next page of hallucination correctors after reaching the limit.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[HallucinationCorrector, ListHallucinationCorrectorsResponse]
            The response includes a list of available correctors and a `page_key` for pagination.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v2/hallucination_correctors",
            base_url=self._client_wrapper.get_environment().default,
            method="GET",
            params={
                "filter": filter,
                "limit": limit,
                "page_key": page_key,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _parsed_response = typing.cast(
                    ListHallucinationCorrectorsResponse,
                    parse_obj_as(
                        type_=ListHallucinationCorrectorsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                _items = _parsed_response.hallucination_correctors
                _has_next = False
                _get_next = None
                if _parsed_response.metadata is not None:
                    _parsed_next = _parsed_response.metadata.page_key
                    _has_next = _parsed_next is not None and _parsed_next != ""
                    _get_next = lambda: self.list(
                        filter=filter,
                        limit=limit,
                        page_key=_parsed_next,
                        request_options=request_options,
                    )
                return SyncPager(has_next=_has_next, items=_items, get_next=_get_next, response=_parsed_response)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def hallucination_correction(
        self,
        *,
        generated_text: str,
        documents: typing.Sequence[HcmSourceDocument],
        model_name: str,
        query: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[HallucinationCorrectionResponse]:
        """
        The Hallucination Correctors API enables users to automatically detect and correct factual inaccuracies, commonly referred to as hallucinations, in generated summaries or responses. By comparing a user-provided summary against one or more source documents, the API returns a corrected version of the summary with minimal necessary edits.

        Use this API to validate and improve the factual accuracy of summaries generated by LLMs in Retrieval Augmented Generation (RAG) pipelines, ensuring that the output remains grounded in trusted source content. If HCM does not detect hallucination, it preserves the original summary.

        The response corrects the original summary. If the input summary is accurate, the `corrected_summary` matches the `original_summary`.

        ## Interpreting empty corrections

        In some cases, the `corrected_text` field in the response may be an empty string. This indicates VHC determined that the entire input text was hallucinated, and VHC recommends removing it completely.

        This outcome is valid and typically occurs when none of the content in the `generated_text` is supported by the provided source documents or query. The response still includes an explanation of why VHC removed the text.

        Parameters
        ----------
        generated_text : str
            The generated text to be evaluated. The hallucination corrector reviews this text and applies corrections based on the provided source documents.

        documents : typing.Sequence[HcmSourceDocument]
            The source documents that were used to generate the text.

        model_name : str
            The name of the LLM model to use for hallucination correction.

        query : typing.Optional[str]
            Optional query that provides context for the expected response format and factual information. When provided, enables query-aware hallucination correction that considers the specific response format and factual context expected for the query.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[HallucinationCorrectionResponse]
            Successfully analyzed the text for hallucinations
        """
        _response = self._client_wrapper.httpx_client.request(
            "v2/hallucination_correctors/correct_hallucinations",
            base_url=self._client_wrapper.get_environment().default,
            method="POST",
            json={
                "generated_text": generated_text,
                "documents": convert_and_respect_annotation_metadata(
                    object_=documents, annotation=typing.Sequence[HcmSourceDocument], direction="write"
                ),
                "model_name": model_name,
                "query": query,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    HallucinationCorrectionResponse,
                    parse_obj_as(
                        type_=HallucinationCorrectionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawHallucinationCorrectorsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self,
        *,
        filter: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        page_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[HallucinationCorrector, ListHallucinationCorrectorsResponse]:
        """
        The List Hallucination Correctors API enables users to list available hallucination correctors used for detecting and correcting hallucinations in AI-generated content. Vectara provides these models as part of its broader hallucination evaluation framework, and the Hallucination Correctors endpoint uses these models to propose factual corrections to summaries and other generative outputs.

        Use this API to inspect available correctors, filter results, and determine which hallucination corrector to reference in downstream workflows or evaluation pipelines.

        Parameters
        ----------
        filter : typing.Optional[str]
            A regular expression applied to the name and description fields. Use this to return only hallucination correctors that match specific keywords or naming conventions.

        limit : typing.Optional[int]
            The maximum number of hallucination correctors to return in the list. Defaults to 10. Range is between 1 and 100.

        page_key : typing.Optional[str]
            Retrieves the next page of hallucination correctors after reaching the limit.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[HallucinationCorrector, ListHallucinationCorrectorsResponse]
            The response includes a list of available correctors and a `page_key` for pagination.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v2/hallucination_correctors",
            base_url=self._client_wrapper.get_environment().default,
            method="GET",
            params={
                "filter": filter,
                "limit": limit,
                "page_key": page_key,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _parsed_response = typing.cast(
                    ListHallucinationCorrectorsResponse,
                    parse_obj_as(
                        type_=ListHallucinationCorrectorsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                _items = _parsed_response.hallucination_correctors
                _has_next = False
                _get_next = None
                if _parsed_response.metadata is not None:
                    _parsed_next = _parsed_response.metadata.page_key
                    _has_next = _parsed_next is not None and _parsed_next != ""

                    async def _get_next():
                        return await self.list(
                            filter=filter,
                            limit=limit,
                            page_key=_parsed_next,
                            request_options=request_options,
                        )

                return AsyncPager(has_next=_has_next, items=_items, get_next=_get_next, response=_parsed_response)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def hallucination_correction(
        self,
        *,
        generated_text: str,
        documents: typing.Sequence[HcmSourceDocument],
        model_name: str,
        query: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[HallucinationCorrectionResponse]:
        """
        The Hallucination Correctors API enables users to automatically detect and correct factual inaccuracies, commonly referred to as hallucinations, in generated summaries or responses. By comparing a user-provided summary against one or more source documents, the API returns a corrected version of the summary with minimal necessary edits.

        Use this API to validate and improve the factual accuracy of summaries generated by LLMs in Retrieval Augmented Generation (RAG) pipelines, ensuring that the output remains grounded in trusted source content. If HCM does not detect hallucination, it preserves the original summary.

        The response corrects the original summary. If the input summary is accurate, the `corrected_summary` matches the `original_summary`.

        ## Interpreting empty corrections

        In some cases, the `corrected_text` field in the response may be an empty string. This indicates VHC determined that the entire input text was hallucinated, and VHC recommends removing it completely.

        This outcome is valid and typically occurs when none of the content in the `generated_text` is supported by the provided source documents or query. The response still includes an explanation of why VHC removed the text.

        Parameters
        ----------
        generated_text : str
            The generated text to be evaluated. The hallucination corrector reviews this text and applies corrections based on the provided source documents.

        documents : typing.Sequence[HcmSourceDocument]
            The source documents that were used to generate the text.

        model_name : str
            The name of the LLM model to use for hallucination correction.

        query : typing.Optional[str]
            Optional query that provides context for the expected response format and factual information. When provided, enables query-aware hallucination correction that considers the specific response format and factual context expected for the query.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[HallucinationCorrectionResponse]
            Successfully analyzed the text for hallucinations
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v2/hallucination_correctors/correct_hallucinations",
            base_url=self._client_wrapper.get_environment().default,
            method="POST",
            json={
                "generated_text": generated_text,
                "documents": convert_and_respect_annotation_metadata(
                    object_=documents, annotation=typing.Sequence[HcmSourceDocument], direction="write"
                ),
                "model_name": model_name,
                "query": query,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    HallucinationCorrectionResponse,
                    parse_obj_as(
                        type_=HallucinationCorrectionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
