# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.pagination import AsyncPager, SyncPager
from ..core.request_options import RequestOptions
from ..types.create_encoder_request import CreateEncoderRequest
from ..types.encoder import Encoder
from ..types.list_encoders_response import ListEncodersResponse
from .raw_client import AsyncRawEncodersClient, RawEncodersClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class EncodersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawEncodersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawEncodersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawEncodersClient
        """
        return self._raw_client

    def list(
        self,
        *,
        filter: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        page_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[Encoder, ListEncodersResponse]:
        """
        The List Encoders API retrieves a list of available encoders used for embedding documents and queries.

        Parameters
        ----------
        filter : typing.Optional[str]
            A regular expression against encoder names and descriptions.

        limit : typing.Optional[int]
            The maximum number of results to return in the list.

        page_key : typing.Optional[str]
            Used to retrieve the next page of encoders after the limit has been reached.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[Encoder, ListEncodersResponse]
            List of encoders.

        Examples
        --------
        from vectara import Vectara

        client = Vectara(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        response = client.encoders.list(
            filter="vectara.*",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list(filter=filter, limit=limit, page_key=page_key, request_options=request_options)

    def create(
        self, *, request: CreateEncoderRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> Encoder:
        """
        Create a new encoder.

        Parameters
        ----------
        request : CreateEncoderRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Encoder
            The encoder has been created

        Examples
        --------
        from vectara import CreateEncoderRequest_OpenaiCompatible, Vectara

        client = Vectara(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.encoders.create(
            request=CreateEncoderRequest_OpenaiCompatible(
                name="openai-text-encoder",
                description="description",
                uri="https://api.openai.com/v1/embeddings",
                model="text-embedding-ada-002",
            ),
        )
        """
        _response = self._raw_client.create(request=request, request_options=request_options)
        return _response.data


class AsyncEncodersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawEncodersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawEncodersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawEncodersClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        filter: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        page_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[Encoder, ListEncodersResponse]:
        """
        The List Encoders API retrieves a list of available encoders used for embedding documents and queries.

        Parameters
        ----------
        filter : typing.Optional[str]
            A regular expression against encoder names and descriptions.

        limit : typing.Optional[int]
            The maximum number of results to return in the list.

        page_key : typing.Optional[str]
            Used to retrieve the next page of encoders after the limit has been reached.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[Encoder, ListEncodersResponse]
            List of encoders.

        Examples
        --------
        import asyncio

        from vectara import AsyncVectara

        client = AsyncVectara(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            response = await client.encoders.list(
                filter="vectara.*",
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list(
            filter=filter, limit=limit, page_key=page_key, request_options=request_options
        )

    async def create(
        self, *, request: CreateEncoderRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> Encoder:
        """
        Create a new encoder.

        Parameters
        ----------
        request : CreateEncoderRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Encoder
            The encoder has been created

        Examples
        --------
        import asyncio

        from vectara import AsyncVectara, CreateEncoderRequest_OpenaiCompatible

        client = AsyncVectara(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.encoders.create(
                request=CreateEncoderRequest_OpenaiCompatible(
                    name="openai-text-encoder",
                    description="description",
                    uri="https://api.openai.com/v1/embeddings",
                    model="text-embedding-ada-002",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(request=request, request_options=request_options)
        return _response.data
