# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.pagination import AsyncPager, SyncPager
from ..core.request_options import RequestOptions
from ..types.generation_preset import GenerationPreset
from ..types.list_generation_presets_response import ListGenerationPresetsResponse
from .raw_client import AsyncRawGenerationPresetsClient, RawGenerationPresetsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class GenerationPresetsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawGenerationPresetsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawGenerationPresetsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawGenerationPresetsClient
        """
        return self._raw_client

    def list(
        self,
        *,
        llm_name: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        page_key: typing.Optional[str] = None,
        request_timeout: typing.Optional[int] = None,
        request_timeout_millis: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[GenerationPreset, ListGenerationPresetsResponse]:
        """
        Organizations often struggle to fine-tune query responses and maintain consistency across different use cases. Vectara creates and maintains predefined generation presets for our users which provides a flexible and powerful way to utilize generation parameters. Each preset includes a complete Velocity template for the prompt along with other generation parameters. Presets are typically associated with a single LLM.

        The List Generation Presets API lets you view the generation presets used for [query](/docs/rest-api/queries) requests. Generation presets group several properties that configure generation for a request. These presets provide more flexibility in how generation parameters are configured, enabling more fine-tuned control over query responses.

        This includes the `prompt_template`, the Large Language Model (LLM), and other generation settings like `max_tokens` and `temperature`. Users specify a generation preset in their query or chat requests using the `generation_preset_name` field.

        ## Generation presets object

        The `generation_presets` object contains the `name`, `description`, `llm_name`, `prompt_template`, and other fields make up the preset.

        If your account has access to a preset, then `enabled` is set to `true`. A preset can also be set as a `default`.\\n\\n### Example generation presets response\\n\\n```json\\n{\\n  \\"generation_presets\\": [\\n    {\\n      \\"name\\": \\"vectara-summary-ext-24-05-med-omni\\",\\n      \\"description\\": \\"Generate summary with controllable citations, Uses GPT-4o with 2,048 max tokens\\",\\n      \\"llm_name\\": \\"gpt-4o\\",\\n      \\"prompt_template\\": \\"[\\\\n    {\\\\\\"role\\\\\\": \\\\\\"system\\\\\\", \\\\\\"content\\\\\\": \\\\\\"Follow these detailed step-by-step\\",\\n      \\"max_used_search_results\\": 25,\\n      \\"max_tokens\\": 2048,\\n      \\"temperature\\": 0,\\n      \\"frequency_penalty\\": 0,\\n      \\"presence_penalty\\": 0,\\n      \\"enabled\\": true,\\n      \\"default\\": false\\n    },\\n    // More presets appear here\\n}\\n```\\n"

        Parameters
        ----------
        llm_name : typing.Optional[str]
            Filter presets by the LLM name.

        limit : typing.Optional[int]
            The maximum number of results to return in the list.

        page_key : typing.Optional[str]
            Used to retrieve the next page of generation presets after the limit has been reached. This parameter is not needed for the first page of results.

        request_timeout : typing.Optional[int]
            The API will make a best effort to complete the request in the specified seconds or time out.

        request_timeout_millis : typing.Optional[int]
            The API will make a best effort to complete the request in the specified milliseconds or time out.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[GenerationPreset, ListGenerationPresetsResponse]
            List of Generation Presets.

        Examples
        --------
        from vectara import Vectara

        client = Vectara()
        response = client.generation_presets.list(
            llm_name="mockingbird-2.0",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list(
            llm_name=llm_name,
            limit=limit,
            page_key=page_key,
            request_timeout=request_timeout,
            request_timeout_millis=request_timeout_millis,
            request_options=request_options,
        )

    def create(
        self,
        *,
        request_timeout: typing.Optional[int] = None,
        request_timeout_millis: typing.Optional[int] = None,
        id: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        llm_name: typing.Optional[str] = OMIT,
        prompt_template: typing.Optional[str] = OMIT,
        max_used_search_results: typing.Optional[int] = OMIT,
        max_tokens: typing.Optional[int] = OMIT,
        temperature: typing.Optional[float] = OMIT,
        frequency_penalty: typing.Optional[float] = OMIT,
        presence_penalty: typing.Optional[float] = OMIT,
        additional_model_params: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        enabled: typing.Optional[bool] = OMIT,
        default: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GenerationPreset:
        """
        Create a custom generation preset for use in query and chat requests. A generation preset bundles a prompt template, an LLM, and model parameters into a reusable configuration.

        The created preset can be referenced by name using the `generation_preset_name` field in query or chat requests.

        Parameters
        ----------
        request_timeout : typing.Optional[int]
            The API will make a best effort to complete the request in the specified seconds or time out.

        request_timeout_millis : typing.Optional[int]
            The API will make a best effort to complete the request in the specified milliseconds or time out.

        id : typing.Optional[str]
            The ID of the generation preset.

        name : typing.Optional[str]
            Name of the generation preset to be used with configuring generation.

        description : typing.Optional[str]
            Description of the generation preset.

        llm_name : typing.Optional[str]
            Name of the model that these presets are used with. The list of available names can be fetched by the `GET /v2/llms` endpoint.

        prompt_template : typing.Optional[str]
            Preset template used to render the prompt sent to generation.

        max_used_search_results : typing.Optional[int]
            Preset maximum number of search results that will be available to the prompt.

        max_tokens : typing.Optional[int]
            Preset maximum number of tokens to be returned by the generation.

        temperature : typing.Optional[float]
            The sampling temperature to use. Higher values make the output more random, while lower values make it more focused and deterministic.

        frequency_penalty : typing.Optional[float]
            Higher values penalize new tokens based on their existing frequency in the generation so far, decreasing the model's likelihood to repeat the same line verbatim.

        presence_penalty : typing.Optional[float]
            Higher values penalize new tokens based on whether they appear in the generation so far, increasing the model's likelihood to talk about new topics.

        additional_model_params : typing.Optional[typing.Dict[str, typing.Any]]
            Additional model parameters beyond the standard fields above.

        enabled : typing.Optional[bool]
            Indicates whether the prompt is enabled.

        default : typing.Optional[bool]
            Indicates if this prompt is the default prompt used with the LLM.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GenerationPreset
            The created generation preset.

        Examples
        --------
        from vectara import Vectara

        client = Vectara()
        client.generation_presets.create()
        """
        _response = self._raw_client.create(
            request_timeout=request_timeout,
            request_timeout_millis=request_timeout_millis,
            id=id,
            name=name,
            description=description,
            llm_name=llm_name,
            prompt_template=prompt_template,
            max_used_search_results=max_used_search_results,
            max_tokens=max_tokens,
            temperature=temperature,
            frequency_penalty=frequency_penalty,
            presence_penalty=presence_penalty,
            additional_model_params=additional_model_params,
            enabled=enabled,
            default=default,
            request_options=request_options,
        )
        return _response.data

    def replace(
        self,
        generation_preset_id: str,
        *,
        request_timeout: typing.Optional[int] = None,
        request_timeout_millis: typing.Optional[int] = None,
        id: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        llm_name: typing.Optional[str] = OMIT,
        prompt_template: typing.Optional[str] = OMIT,
        max_used_search_results: typing.Optional[int] = OMIT,
        max_tokens: typing.Optional[int] = OMIT,
        temperature: typing.Optional[float] = OMIT,
        frequency_penalty: typing.Optional[float] = OMIT,
        presence_penalty: typing.Optional[float] = OMIT,
        additional_model_params: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        enabled: typing.Optional[bool] = OMIT,
        default: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GenerationPreset:
        """
        Replace an existing custom generation preset. This performs a full replacement of the preset configuration.
        The preset must have been created by the customer (platform presets cannot be replaced).

        Parameters
        ----------
        generation_preset_id : str
            The ID of the generation preset to replace.

        request_timeout : typing.Optional[int]
            The API will make a best effort to complete the request in the specified seconds or time out.

        request_timeout_millis : typing.Optional[int]
            The API will make a best effort to complete the request in the specified milliseconds or time out.

        id : typing.Optional[str]
            The ID of the generation preset.

        name : typing.Optional[str]
            Name of the generation preset to be used with configuring generation.

        description : typing.Optional[str]
            Description of the generation preset.

        llm_name : typing.Optional[str]
            Name of the model that these presets are used with. The list of available names can be fetched by the `GET /v2/llms` endpoint.

        prompt_template : typing.Optional[str]
            Preset template used to render the prompt sent to generation.

        max_used_search_results : typing.Optional[int]
            Preset maximum number of search results that will be available to the prompt.

        max_tokens : typing.Optional[int]
            Preset maximum number of tokens to be returned by the generation.

        temperature : typing.Optional[float]
            The sampling temperature to use. Higher values make the output more random, while lower values make it more focused and deterministic.

        frequency_penalty : typing.Optional[float]
            Higher values penalize new tokens based on their existing frequency in the generation so far, decreasing the model's likelihood to repeat the same line verbatim.

        presence_penalty : typing.Optional[float]
            Higher values penalize new tokens based on whether they appear in the generation so far, increasing the model's likelihood to talk about new topics.

        additional_model_params : typing.Optional[typing.Dict[str, typing.Any]]
            Additional model parameters beyond the standard fields above.

        enabled : typing.Optional[bool]
            Indicates whether the prompt is enabled.

        default : typing.Optional[bool]
            Indicates if this prompt is the default prompt used with the LLM.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GenerationPreset
            The replaced generation preset.

        Examples
        --------
        from vectara import Vectara

        client = Vectara()
        client.generation_presets.replace(
            generation_preset_id="generation_preset_id",
        )
        """
        _response = self._raw_client.replace(
            generation_preset_id,
            request_timeout=request_timeout,
            request_timeout_millis=request_timeout_millis,
            id=id,
            name=name,
            description=description,
            llm_name=llm_name,
            prompt_template=prompt_template,
            max_used_search_results=max_used_search_results,
            max_tokens=max_tokens,
            temperature=temperature,
            frequency_penalty=frequency_penalty,
            presence_penalty=presence_penalty,
            additional_model_params=additional_model_params,
            enabled=enabled,
            default=default,
            request_options=request_options,
        )
        return _response.data

    def delete(
        self,
        generation_preset_id: str,
        *,
        request_timeout: typing.Optional[int] = None,
        request_timeout_millis: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Delete an existing custom generation preset.
        The preset must have been created by the customer (platform presets cannot be deleted).

        Parameters
        ----------
        generation_preset_id : str
            The ID of the generation preset to delete.

        request_timeout : typing.Optional[int]
            The API will make a best effort to complete the request in the specified seconds or time out.

        request_timeout_millis : typing.Optional[int]
            The API will make a best effort to complete the request in the specified milliseconds or time out.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from vectara import Vectara

        client = Vectara()
        client.generation_presets.delete(
            generation_preset_id="generation_preset_id",
        )
        """
        _response = self._raw_client.delete(
            generation_preset_id,
            request_timeout=request_timeout,
            request_timeout_millis=request_timeout_millis,
            request_options=request_options,
        )
        return _response.data


class AsyncGenerationPresetsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawGenerationPresetsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawGenerationPresetsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawGenerationPresetsClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        llm_name: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        page_key: typing.Optional[str] = None,
        request_timeout: typing.Optional[int] = None,
        request_timeout_millis: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[GenerationPreset, ListGenerationPresetsResponse]:
        """
        Organizations often struggle to fine-tune query responses and maintain consistency across different use cases. Vectara creates and maintains predefined generation presets for our users which provides a flexible and powerful way to utilize generation parameters. Each preset includes a complete Velocity template for the prompt along with other generation parameters. Presets are typically associated with a single LLM.

        The List Generation Presets API lets you view the generation presets used for [query](/docs/rest-api/queries) requests. Generation presets group several properties that configure generation for a request. These presets provide more flexibility in how generation parameters are configured, enabling more fine-tuned control over query responses.

        This includes the `prompt_template`, the Large Language Model (LLM), and other generation settings like `max_tokens` and `temperature`. Users specify a generation preset in their query or chat requests using the `generation_preset_name` field.

        ## Generation presets object

        The `generation_presets` object contains the `name`, `description`, `llm_name`, `prompt_template`, and other fields make up the preset.

        If your account has access to a preset, then `enabled` is set to `true`. A preset can also be set as a `default`.\\n\\n### Example generation presets response\\n\\n```json\\n{\\n  \\"generation_presets\\": [\\n    {\\n      \\"name\\": \\"vectara-summary-ext-24-05-med-omni\\",\\n      \\"description\\": \\"Generate summary with controllable citations, Uses GPT-4o with 2,048 max tokens\\",\\n      \\"llm_name\\": \\"gpt-4o\\",\\n      \\"prompt_template\\": \\"[\\\\n    {\\\\\\"role\\\\\\": \\\\\\"system\\\\\\", \\\\\\"content\\\\\\": \\\\\\"Follow these detailed step-by-step\\",\\n      \\"max_used_search_results\\": 25,\\n      \\"max_tokens\\": 2048,\\n      \\"temperature\\": 0,\\n      \\"frequency_penalty\\": 0,\\n      \\"presence_penalty\\": 0,\\n      \\"enabled\\": true,\\n      \\"default\\": false\\n    },\\n    // More presets appear here\\n}\\n```\\n"

        Parameters
        ----------
        llm_name : typing.Optional[str]
            Filter presets by the LLM name.

        limit : typing.Optional[int]
            The maximum number of results to return in the list.

        page_key : typing.Optional[str]
            Used to retrieve the next page of generation presets after the limit has been reached. This parameter is not needed for the first page of results.

        request_timeout : typing.Optional[int]
            The API will make a best effort to complete the request in the specified seconds or time out.

        request_timeout_millis : typing.Optional[int]
            The API will make a best effort to complete the request in the specified milliseconds or time out.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[GenerationPreset, ListGenerationPresetsResponse]
            List of Generation Presets.

        Examples
        --------
        import asyncio

        from vectara import AsyncVectara

        client = AsyncVectara()


        async def main() -> None:
            response = await client.generation_presets.list(
                llm_name="mockingbird-2.0",
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list(
            llm_name=llm_name,
            limit=limit,
            page_key=page_key,
            request_timeout=request_timeout,
            request_timeout_millis=request_timeout_millis,
            request_options=request_options,
        )

    async def create(
        self,
        *,
        request_timeout: typing.Optional[int] = None,
        request_timeout_millis: typing.Optional[int] = None,
        id: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        llm_name: typing.Optional[str] = OMIT,
        prompt_template: typing.Optional[str] = OMIT,
        max_used_search_results: typing.Optional[int] = OMIT,
        max_tokens: typing.Optional[int] = OMIT,
        temperature: typing.Optional[float] = OMIT,
        frequency_penalty: typing.Optional[float] = OMIT,
        presence_penalty: typing.Optional[float] = OMIT,
        additional_model_params: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        enabled: typing.Optional[bool] = OMIT,
        default: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GenerationPreset:
        """
        Create a custom generation preset for use in query and chat requests. A generation preset bundles a prompt template, an LLM, and model parameters into a reusable configuration.

        The created preset can be referenced by name using the `generation_preset_name` field in query or chat requests.

        Parameters
        ----------
        request_timeout : typing.Optional[int]
            The API will make a best effort to complete the request in the specified seconds or time out.

        request_timeout_millis : typing.Optional[int]
            The API will make a best effort to complete the request in the specified milliseconds or time out.

        id : typing.Optional[str]
            The ID of the generation preset.

        name : typing.Optional[str]
            Name of the generation preset to be used with configuring generation.

        description : typing.Optional[str]
            Description of the generation preset.

        llm_name : typing.Optional[str]
            Name of the model that these presets are used with. The list of available names can be fetched by the `GET /v2/llms` endpoint.

        prompt_template : typing.Optional[str]
            Preset template used to render the prompt sent to generation.

        max_used_search_results : typing.Optional[int]
            Preset maximum number of search results that will be available to the prompt.

        max_tokens : typing.Optional[int]
            Preset maximum number of tokens to be returned by the generation.

        temperature : typing.Optional[float]
            The sampling temperature to use. Higher values make the output more random, while lower values make it more focused and deterministic.

        frequency_penalty : typing.Optional[float]
            Higher values penalize new tokens based on their existing frequency in the generation so far, decreasing the model's likelihood to repeat the same line verbatim.

        presence_penalty : typing.Optional[float]
            Higher values penalize new tokens based on whether they appear in the generation so far, increasing the model's likelihood to talk about new topics.

        additional_model_params : typing.Optional[typing.Dict[str, typing.Any]]
            Additional model parameters beyond the standard fields above.

        enabled : typing.Optional[bool]
            Indicates whether the prompt is enabled.

        default : typing.Optional[bool]
            Indicates if this prompt is the default prompt used with the LLM.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GenerationPreset
            The created generation preset.

        Examples
        --------
        import asyncio

        from vectara import AsyncVectara

        client = AsyncVectara()


        async def main() -> None:
            await client.generation_presets.create()


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            request_timeout=request_timeout,
            request_timeout_millis=request_timeout_millis,
            id=id,
            name=name,
            description=description,
            llm_name=llm_name,
            prompt_template=prompt_template,
            max_used_search_results=max_used_search_results,
            max_tokens=max_tokens,
            temperature=temperature,
            frequency_penalty=frequency_penalty,
            presence_penalty=presence_penalty,
            additional_model_params=additional_model_params,
            enabled=enabled,
            default=default,
            request_options=request_options,
        )
        return _response.data

    async def replace(
        self,
        generation_preset_id: str,
        *,
        request_timeout: typing.Optional[int] = None,
        request_timeout_millis: typing.Optional[int] = None,
        id: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        llm_name: typing.Optional[str] = OMIT,
        prompt_template: typing.Optional[str] = OMIT,
        max_used_search_results: typing.Optional[int] = OMIT,
        max_tokens: typing.Optional[int] = OMIT,
        temperature: typing.Optional[float] = OMIT,
        frequency_penalty: typing.Optional[float] = OMIT,
        presence_penalty: typing.Optional[float] = OMIT,
        additional_model_params: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        enabled: typing.Optional[bool] = OMIT,
        default: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GenerationPreset:
        """
        Replace an existing custom generation preset. This performs a full replacement of the preset configuration.
        The preset must have been created by the customer (platform presets cannot be replaced).

        Parameters
        ----------
        generation_preset_id : str
            The ID of the generation preset to replace.

        request_timeout : typing.Optional[int]
            The API will make a best effort to complete the request in the specified seconds or time out.

        request_timeout_millis : typing.Optional[int]
            The API will make a best effort to complete the request in the specified milliseconds or time out.

        id : typing.Optional[str]
            The ID of the generation preset.

        name : typing.Optional[str]
            Name of the generation preset to be used with configuring generation.

        description : typing.Optional[str]
            Description of the generation preset.

        llm_name : typing.Optional[str]
            Name of the model that these presets are used with. The list of available names can be fetched by the `GET /v2/llms` endpoint.

        prompt_template : typing.Optional[str]
            Preset template used to render the prompt sent to generation.

        max_used_search_results : typing.Optional[int]
            Preset maximum number of search results that will be available to the prompt.

        max_tokens : typing.Optional[int]
            Preset maximum number of tokens to be returned by the generation.

        temperature : typing.Optional[float]
            The sampling temperature to use. Higher values make the output more random, while lower values make it more focused and deterministic.

        frequency_penalty : typing.Optional[float]
            Higher values penalize new tokens based on their existing frequency in the generation so far, decreasing the model's likelihood to repeat the same line verbatim.

        presence_penalty : typing.Optional[float]
            Higher values penalize new tokens based on whether they appear in the generation so far, increasing the model's likelihood to talk about new topics.

        additional_model_params : typing.Optional[typing.Dict[str, typing.Any]]
            Additional model parameters beyond the standard fields above.

        enabled : typing.Optional[bool]
            Indicates whether the prompt is enabled.

        default : typing.Optional[bool]
            Indicates if this prompt is the default prompt used with the LLM.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GenerationPreset
            The replaced generation preset.

        Examples
        --------
        import asyncio

        from vectara import AsyncVectara

        client = AsyncVectara()


        async def main() -> None:
            await client.generation_presets.replace(
                generation_preset_id="generation_preset_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.replace(
            generation_preset_id,
            request_timeout=request_timeout,
            request_timeout_millis=request_timeout_millis,
            id=id,
            name=name,
            description=description,
            llm_name=llm_name,
            prompt_template=prompt_template,
            max_used_search_results=max_used_search_results,
            max_tokens=max_tokens,
            temperature=temperature,
            frequency_penalty=frequency_penalty,
            presence_penalty=presence_penalty,
            additional_model_params=additional_model_params,
            enabled=enabled,
            default=default,
            request_options=request_options,
        )
        return _response.data

    async def delete(
        self,
        generation_preset_id: str,
        *,
        request_timeout: typing.Optional[int] = None,
        request_timeout_millis: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Delete an existing custom generation preset.
        The preset must have been created by the customer (platform presets cannot be deleted).

        Parameters
        ----------
        generation_preset_id : str
            The ID of the generation preset to delete.

        request_timeout : typing.Optional[int]
            The API will make a best effort to complete the request in the specified seconds or time out.

        request_timeout_millis : typing.Optional[int]
            The API will make a best effort to complete the request in the specified milliseconds or time out.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from vectara import AsyncVectara

        client = AsyncVectara()


        async def main() -> None:
            await client.generation_presets.delete(
                generation_preset_id="generation_preset_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(
            generation_preset_id,
            request_timeout=request_timeout,
            request_timeout_millis=request_timeout_millis,
            request_options=request_options,
        )
        return _response.data
